// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file RpcReqMsg.cpp
 * This source file contains the implementation of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "RpcReqMsg.h"

#include <fastcdr/Cdr.h>


#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

namespace helper { namespace internal {

enum class Size {
    UInt8,
    UInt16,
    UInt32,
    UInt64,
};

constexpr Size get_size(int s) {
    return (s <= 8 ) ? Size::UInt8:
           (s <= 16) ? Size::UInt16:
           (s <= 32) ? Size::UInt32: Size::UInt64;
}

template<Size s>
struct FindTypeH;

template<>
struct FindTypeH<Size::UInt8> {
    using type = std::uint8_t;
};

template<>
struct FindTypeH<Size::UInt16> {
    using type = std::uint16_t;
};

template<>
struct FindTypeH<Size::UInt32> {
    using type = std::uint32_t;
};

template<>
struct FindTypeH<Size::UInt64> {
    using type = std::uint64_t;
};
}

template<int S>
struct FindType {
    using type = typename internal::FindTypeH<internal::get_size(S)>::type;
};
}

#define booster_msgs_msg_dds__RpcReqMsg__max_cdr_typesize 780ULL;


namespace booster_msgs {

namespace msg {

namespace dds_ {



RpcReqMsg_::RpcReqMsg_()
{
    // /type_d() m_uuid

    // /type_d() m_header

    // /type_d() m_body


}

RpcReqMsg_::~RpcReqMsg_()
{
}

RpcReqMsg_::RpcReqMsg_(
        const RpcReqMsg_& x)
{
    m_uuid = x.m_uuid;


    m_header = x.m_header;


    m_body = x.m_body;

}

RpcReqMsg_::RpcReqMsg_(
        RpcReqMsg_&& x) noexcept
{
    m_uuid = std::move(x.m_uuid);


    m_header = std::move(x.m_header);


    m_body = std::move(x.m_body);

}

RpcReqMsg_& RpcReqMsg_::operator =(
        const RpcReqMsg_& x)
{
    m_uuid = x.m_uuid;


    m_header = x.m_header;


    m_body = x.m_body;

    return *this;
}

RpcReqMsg_& RpcReqMsg_::operator =(
        RpcReqMsg_&& x) noexcept
{
    m_uuid = std::move(x.m_uuid);


    m_header = std::move(x.m_header);


    m_body = std::move(x.m_body);

    return *this;
}

bool RpcReqMsg_::operator ==(
        const RpcReqMsg_& x) const
{
    return (m_uuid == x.m_uuid &&
           m_header == x.m_header &&
           m_body == x.m_body);
}

bool RpcReqMsg_::operator !=(
        const RpcReqMsg_& x) const
{
    return !(*this == x);
}

size_t RpcReqMsg_::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    static_cast<void>(current_alignment);
    return booster_msgs_msg_dds__RpcReqMsg__max_cdr_typesize;
}

size_t RpcReqMsg_::getCdrSerializedSize(
        const RpcReqMsg_& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;

    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4) + data.uuid().size() + 1;


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4) + data.header().size() + 1;


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4) + data.body().size() + 1;


    return current_alignment - initial_alignment;
}


void RpcReqMsg_::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{
    scdr << m_uuid.c_str();

    scdr << m_header.c_str();

    scdr << m_body.c_str();

}

void RpcReqMsg_::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{
    dcdr >> m_uuid;



    dcdr >> m_header;



    dcdr >> m_body;


}


bool RpcReqMsg_::isKeyDefined()
{
    return false;
}

void RpcReqMsg_::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
}

/*!
 * @brief This function copies the value in member uuid
 * @param _uuid New value to be copied in member uuid
 */
void RpcReqMsg_::uuid(
        const std::string& _uuid)
{
    m_uuid = _uuid;
}

/*!
 * @brief This function moves the value in member uuid
 * @param _uuid New value to be moved in member uuid
 */
void RpcReqMsg_::uuid(
        std::string&& _uuid)
{
    m_uuid = std::move(_uuid);
}

/*!
 * @brief This function returns a constant reference to member uuid
 * @return Constant reference to member uuid
 */
const std::string& RpcReqMsg_::uuid() const
{
    return m_uuid;
}

/*!
 * @brief This function returns a reference to member uuid
 * @return Reference to member uuid
 */
std::string& RpcReqMsg_::uuid()
{
    return m_uuid;
}


/*!
 * @brief This function copies the value in member header
 * @param _header New value to be copied in member header
 */
void RpcReqMsg_::header(
        const std::string& _header)
{
    m_header = _header;
}

/*!
 * @brief This function moves the value in member header
 * @param _header New value to be moved in member header
 */
void RpcReqMsg_::header(
        std::string&& _header)
{
    m_header = std::move(_header);
}

/*!
 * @brief This function returns a constant reference to member header
 * @return Constant reference to member header
 */
const std::string& RpcReqMsg_::header() const
{
    return m_header;
}

/*!
 * @brief This function returns a reference to member header
 * @return Reference to member header
 */
std::string& RpcReqMsg_::header()
{
    return m_header;
}


/*!
 * @brief This function copies the value in member body
 * @param _body New value to be copied in member body
 */
void RpcReqMsg_::body(
        const std::string& _body)
{
    m_body = _body;
}

/*!
 * @brief This function moves the value in member body
 * @param _body New value to be moved in member body
 */
void RpcReqMsg_::body(
        std::string&& _body)
{
    m_body = std::move(_body);
}

/*!
 * @brief This function returns a constant reference to member body
 * @return Constant reference to member body
 */
const std::string& RpcReqMsg_::body() const
{
    return m_body;
}

/*!
 * @brief This function returns a reference to member body
 * @return Reference to member body
 */
std::string& RpcReqMsg_::body()
{
    return m_body;
}





} // namespace dds_


} // namespace msg


} // namespace booster_msgs

