// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file RpcRespMsg.cpp
 * This source file contains the implementation of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "RpcRespMsg.h"

#include <fastcdr/Cdr.h>


#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

namespace helper { namespace internal {

enum class Size {
    UInt8,
    UInt16,
    UInt32,
    UInt64,
};

constexpr Size get_size(int s) {
    return (s <= 8 ) ? Size::UInt8:
           (s <= 16) ? Size::UInt16:
           (s <= 32) ? Size::UInt32: Size::UInt64;
}

template<Size s>
struct FindTypeH;

template<>
struct FindTypeH<Size::UInt8> {
    using type = std::uint8_t;
};

template<>
struct FindTypeH<Size::UInt16> {
    using type = std::uint16_t;
};

template<>
struct FindTypeH<Size::UInt32> {
    using type = std::uint32_t;
};

template<>
struct FindTypeH<Size::UInt64> {
    using type = std::uint64_t;
};
}

template<int S>
struct FindType {
    using type = typename internal::FindTypeH<internal::get_size(S)>::type;
};
}

#define booster_msgs_msg_dds__RpcRespMsg__max_cdr_typesize 780ULL;


namespace booster_msgs {

namespace msg {

namespace dds_ {



RpcRespMsg_::RpcRespMsg_()
{
    // /type_d() m_uuid

    // /type_d() m_header

    // /type_d() m_body


}

RpcRespMsg_::~RpcRespMsg_()
{
}

RpcRespMsg_::RpcRespMsg_(
        const RpcRespMsg_& x)
{
    m_uuid = x.m_uuid;


    m_header = x.m_header;


    m_body = x.m_body;

}

RpcRespMsg_::RpcRespMsg_(
        RpcRespMsg_&& x) noexcept
{
    m_uuid = std::move(x.m_uuid);


    m_header = std::move(x.m_header);


    m_body = std::move(x.m_body);

}

RpcRespMsg_& RpcRespMsg_::operator =(
        const RpcRespMsg_& x)
{
    m_uuid = x.m_uuid;


    m_header = x.m_header;


    m_body = x.m_body;

    return *this;
}

RpcRespMsg_& RpcRespMsg_::operator =(
        RpcRespMsg_&& x) noexcept
{
    m_uuid = std::move(x.m_uuid);


    m_header = std::move(x.m_header);


    m_body = std::move(x.m_body);

    return *this;
}

bool RpcRespMsg_::operator ==(
        const RpcRespMsg_& x) const
{
    return (m_uuid == x.m_uuid &&
           m_header == x.m_header &&
           m_body == x.m_body);
}

bool RpcRespMsg_::operator !=(
        const RpcRespMsg_& x) const
{
    return !(*this == x);
}

size_t RpcRespMsg_::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    static_cast<void>(current_alignment);
    return booster_msgs_msg_dds__RpcRespMsg__max_cdr_typesize;
}

size_t RpcRespMsg_::getCdrSerializedSize(
        const RpcRespMsg_& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;

    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4) + data.uuid().size() + 1;


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4) + data.header().size() + 1;


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4) + data.body().size() + 1;


    return current_alignment - initial_alignment;
}


void RpcRespMsg_::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{
    scdr << m_uuid.c_str();

    scdr << m_header.c_str();

    scdr << m_body.c_str();

}

void RpcRespMsg_::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{
    dcdr >> m_uuid;



    dcdr >> m_header;



    dcdr >> m_body;


}


bool RpcRespMsg_::isKeyDefined()
{
    return false;
}

void RpcRespMsg_::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
}

/*!
 * @brief This function copies the value in member uuid
 * @param _uuid New value to be copied in member uuid
 */
void RpcRespMsg_::uuid(
        const std::string& _uuid)
{
    m_uuid = _uuid;
}

/*!
 * @brief This function moves the value in member uuid
 * @param _uuid New value to be moved in member uuid
 */
void RpcRespMsg_::uuid(
        std::string&& _uuid)
{
    m_uuid = std::move(_uuid);
}

/*!
 * @brief This function returns a constant reference to member uuid
 * @return Constant reference to member uuid
 */
const std::string& RpcRespMsg_::uuid() const
{
    return m_uuid;
}

/*!
 * @brief This function returns a reference to member uuid
 * @return Reference to member uuid
 */
std::string& RpcRespMsg_::uuid()
{
    return m_uuid;
}


/*!
 * @brief This function copies the value in member header
 * @param _header New value to be copied in member header
 */
void RpcRespMsg_::header(
        const std::string& _header)
{
    m_header = _header;
}

/*!
 * @brief This function moves the value in member header
 * @param _header New value to be moved in member header
 */
void RpcRespMsg_::header(
        std::string&& _header)
{
    m_header = std::move(_header);
}

/*!
 * @brief This function returns a constant reference to member header
 * @return Constant reference to member header
 */
const std::string& RpcRespMsg_::header() const
{
    return m_header;
}

/*!
 * @brief This function returns a reference to member header
 * @return Reference to member header
 */
std::string& RpcRespMsg_::header()
{
    return m_header;
}


/*!
 * @brief This function copies the value in member body
 * @param _body New value to be copied in member body
 */
void RpcRespMsg_::body(
        const std::string& _body)
{
    m_body = _body;
}

/*!
 * @brief This function moves the value in member body
 * @param _body New value to be moved in member body
 */
void RpcRespMsg_::body(
        std::string&& _body)
{
    m_body = std::move(_body);
}

/*!
 * @brief This function returns a constant reference to member body
 * @return Constant reference to member body
 */
const std::string& RpcRespMsg_::body() const
{
    return m_body;
}

/*!
 * @brief This function returns a reference to member body
 * @return Reference to member body
 */
std::string& RpcRespMsg_::body()
{
    return m_body;
}





} // namespace dds_


} // namespace msg


} // namespace booster_msgs

