// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file Header.cpp
 * This source file contains the implementation of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "Header.h"

#include <fastcdr/Cdr.h>


#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

namespace helper { namespace internal {

enum class Size {
    UInt8,
    UInt16,
    UInt32,
    UInt64,
};

constexpr Size get_size(int s) {
    return (s <= 8 ) ? Size::UInt8:
           (s <= 16) ? Size::UInt16:
           (s <= 32) ? Size::UInt32: Size::UInt64;
}

template<Size s>
struct FindTypeH;

template<>
struct FindTypeH<Size::UInt8> {
    using type = std::uint8_t;
};

template<>
struct FindTypeH<Size::UInt16> {
    using type = std::uint16_t;
};

template<>
struct FindTypeH<Size::UInt32> {
    using type = std::uint32_t;
};

template<>
struct FindTypeH<Size::UInt64> {
    using type = std::uint64_t;
};
}

template<int S>
struct FindType {
    using type = typename internal::FindTypeH<internal::get_size(S)>::type;
};
}

#define builtin_interfaces_msg_dds__Time__max_cdr_typesize 8ULL;
#define std_msgs_msg_dds__Header__max_cdr_typesize 268ULL;


namespace std_msgs {

namespace msg {

namespace dds_ {



Header_::Header_()
{
    // builtin_interfaces::msg::dds_::Time_ m_stamp

    // /type_d() m_frame_id


}

Header_::~Header_()
{
}

Header_::Header_(
        const Header_& x)
{
    m_stamp = x.m_stamp;


    m_frame_id = x.m_frame_id;

}

Header_::Header_(
        Header_&& x) noexcept
{
    m_stamp = std::move(x.m_stamp);


    m_frame_id = std::move(x.m_frame_id);

}

Header_& Header_::operator =(
        const Header_& x)
{
    m_stamp = x.m_stamp;


    m_frame_id = x.m_frame_id;

    return *this;
}

Header_& Header_::operator =(
        Header_&& x) noexcept
{
    m_stamp = std::move(x.m_stamp);


    m_frame_id = std::move(x.m_frame_id);

    return *this;
}

bool Header_::operator ==(
        const Header_& x) const
{
    return (m_stamp == x.m_stamp &&
           m_frame_id == x.m_frame_id);
}

bool Header_::operator !=(
        const Header_& x) const
{
    return !(*this == x);
}

size_t Header_::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    static_cast<void>(current_alignment);
    return std_msgs_msg_dds__Header__max_cdr_typesize;
}

size_t Header_::getCdrSerializedSize(
        const Header_& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;

    current_alignment += builtin_interfaces::msg::dds_::Time_::getCdrSerializedSize(data.stamp(), current_alignment);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4) + data.frame_id().size() + 1;


    return current_alignment - initial_alignment;
}


void Header_::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{
    scdr << m_stamp;

    scdr << m_frame_id.c_str();

}

void Header_::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{
    dcdr >> m_stamp;



    dcdr >> m_frame_id;


}


bool Header_::isKeyDefined()
{
    return false;
}

void Header_::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
}

/*!
 * @brief This function copies the value in member stamp
 * @param _stamp New value to be copied in member stamp
 */
void Header_::stamp(
        const builtin_interfaces::msg::dds_::Time_& _stamp)
{
    m_stamp = _stamp;
}

/*!
 * @brief This function moves the value in member stamp
 * @param _stamp New value to be moved in member stamp
 */
void Header_::stamp(
        builtin_interfaces::msg::dds_::Time_&& _stamp)
{
    m_stamp = std::move(_stamp);
}

/*!
 * @brief This function returns a constant reference to member stamp
 * @return Constant reference to member stamp
 */
const builtin_interfaces::msg::dds_::Time_& Header_::stamp() const
{
    return m_stamp;
}

/*!
 * @brief This function returns a reference to member stamp
 * @return Reference to member stamp
 */
builtin_interfaces::msg::dds_::Time_& Header_::stamp()
{
    return m_stamp;
}


/*!
 * @brief This function copies the value in member frame_id
 * @param _frame_id New value to be copied in member frame_id
 */
void Header_::frame_id(
        const std::string& _frame_id)
{
    m_frame_id = _frame_id;
}

/*!
 * @brief This function moves the value in member frame_id
 * @param _frame_id New value to be moved in member frame_id
 */
void Header_::frame_id(
        std::string&& _frame_id)
{
    m_frame_id = std::move(_frame_id);
}

/*!
 * @brief This function returns a constant reference to member frame_id
 * @return Constant reference to member frame_id
 */
const std::string& Header_::frame_id() const
{
    return m_frame_id;
}

/*!
 * @brief This function returns a reference to member frame_id
 * @return Reference to member frame_id
 */
std::string& Header_::frame_id()
{
    return m_frame_id;
}





} // namespace dds_


} // namespace msg


} // namespace std_msgs

