// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file Odometry.cpp
 * This source file contains the implementation of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "Odometry.h"

#include <fastcdr/Cdr.h>


#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

namespace helper { namespace internal {

enum class Size {
    UInt8,
    UInt16,
    UInt32,
    UInt64,
};

constexpr Size get_size(int s) {
    return (s <= 8 ) ? Size::UInt8:
           (s <= 16) ? Size::UInt16:
           (s <= 32) ? Size::UInt32: Size::UInt64;
}

template<Size s>
struct FindTypeH;

template<>
struct FindTypeH<Size::UInt8> {
    using type = std::uint8_t;
};

template<>
struct FindTypeH<Size::UInt16> {
    using type = std::uint16_t;
};

template<>
struct FindTypeH<Size::UInt32> {
    using type = std::uint32_t;
};

template<>
struct FindTypeH<Size::UInt64> {
    using type = std::uint64_t;
};
}

template<int S>
struct FindType {
    using type = typename internal::FindTypeH<internal::get_size(S)>::type;
};
}

#define geometry_msgs_msg_dds__Quaternion__max_cdr_typesize 32ULL;
#define geometry_msgs_msg_dds__Vector3__max_cdr_typesize 24ULL;
#define builtin_interfaces_msg_dds__Time__max_cdr_typesize 8ULL;
#define geometry_msgs_msg_dds__TwistWithCovariance__max_cdr_typesize 336ULL;
#define std_msgs_msg_dds__Header__max_cdr_typesize 268ULL;
#define geometry_msgs_msg_dds__Point__max_cdr_typesize 24ULL;
#define geometry_msgs_msg_dds__Pose__max_cdr_typesize 56ULL;
#define geometry_msgs_msg_dds__Twist__max_cdr_typesize 48ULL;
#define nav_msgs_msg_dds__Odometry__max_cdr_typesize 1208ULL;
#define geometry_msgs_msg_dds__PoseWithCovariance__max_cdr_typesize 344ULL;


namespace nav_msgs {

namespace msg {

namespace dds_ {



Odometry_::Odometry_()
{
    // std_msgs::msg::dds_::Header_ m_header

    // /type_d() m_child_frame_id

    // geometry_msgs::msg::dds_::PoseWithCovariance_ m_pose

    // geometry_msgs::msg::dds_::TwistWithCovariance_ m_twist


}

Odometry_::~Odometry_()
{
}

Odometry_::Odometry_(
        const Odometry_& x)
{
    m_header = x.m_header;


    m_child_frame_id = x.m_child_frame_id;


    m_pose = x.m_pose;


    m_twist = x.m_twist;

}

Odometry_::Odometry_(
        Odometry_&& x) noexcept
{
    m_header = std::move(x.m_header);


    m_child_frame_id = std::move(x.m_child_frame_id);


    m_pose = std::move(x.m_pose);


    m_twist = std::move(x.m_twist);

}

Odometry_& Odometry_::operator =(
        const Odometry_& x)
{
    m_header = x.m_header;


    m_child_frame_id = x.m_child_frame_id;


    m_pose = x.m_pose;


    m_twist = x.m_twist;

    return *this;
}

Odometry_& Odometry_::operator =(
        Odometry_&& x) noexcept
{
    m_header = std::move(x.m_header);


    m_child_frame_id = std::move(x.m_child_frame_id);


    m_pose = std::move(x.m_pose);


    m_twist = std::move(x.m_twist);

    return *this;
}

bool Odometry_::operator ==(
        const Odometry_& x) const
{
    return (m_header == x.m_header &&
           m_child_frame_id == x.m_child_frame_id &&
           m_pose == x.m_pose &&
           m_twist == x.m_twist);
}

bool Odometry_::operator !=(
        const Odometry_& x) const
{
    return !(*this == x);
}

size_t Odometry_::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    static_cast<void>(current_alignment);
    return nav_msgs_msg_dds__Odometry__max_cdr_typesize;
}

size_t Odometry_::getCdrSerializedSize(
        const Odometry_& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;

    current_alignment += std_msgs::msg::dds_::Header_::getCdrSerializedSize(data.header(), current_alignment);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4) + data.child_frame_id().size() + 1;


    current_alignment += geometry_msgs::msg::dds_::PoseWithCovariance_::getCdrSerializedSize(data.pose(), current_alignment);


    current_alignment += geometry_msgs::msg::dds_::TwistWithCovariance_::getCdrSerializedSize(data.twist(), current_alignment);


    return current_alignment - initial_alignment;
}


void Odometry_::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{
    scdr << m_header;

    scdr << m_child_frame_id.c_str();

    scdr << m_pose;

    scdr << m_twist;

}

void Odometry_::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{
    dcdr >> m_header;



    dcdr >> m_child_frame_id;



    dcdr >> m_pose;



    dcdr >> m_twist;


}


bool Odometry_::isKeyDefined()
{
    return false;
}

void Odometry_::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
}

/*!
 * @brief This function copies the value in member header
 * @param _header New value to be copied in member header
 */
void Odometry_::header(
        const std_msgs::msg::dds_::Header_& _header)
{
    m_header = _header;
}

/*!
 * @brief This function moves the value in member header
 * @param _header New value to be moved in member header
 */
void Odometry_::header(
        std_msgs::msg::dds_::Header_&& _header)
{
    m_header = std::move(_header);
}

/*!
 * @brief This function returns a constant reference to member header
 * @return Constant reference to member header
 */
const std_msgs::msg::dds_::Header_& Odometry_::header() const
{
    return m_header;
}

/*!
 * @brief This function returns a reference to member header
 * @return Reference to member header
 */
std_msgs::msg::dds_::Header_& Odometry_::header()
{
    return m_header;
}


/*!
 * @brief This function copies the value in member child_frame_id
 * @param _child_frame_id New value to be copied in member child_frame_id
 */
void Odometry_::child_frame_id(
        const std::string& _child_frame_id)
{
    m_child_frame_id = _child_frame_id;
}

/*!
 * @brief This function moves the value in member child_frame_id
 * @param _child_frame_id New value to be moved in member child_frame_id
 */
void Odometry_::child_frame_id(
        std::string&& _child_frame_id)
{
    m_child_frame_id = std::move(_child_frame_id);
}

/*!
 * @brief This function returns a constant reference to member child_frame_id
 * @return Constant reference to member child_frame_id
 */
const std::string& Odometry_::child_frame_id() const
{
    return m_child_frame_id;
}

/*!
 * @brief This function returns a reference to member child_frame_id
 * @return Reference to member child_frame_id
 */
std::string& Odometry_::child_frame_id()
{
    return m_child_frame_id;
}


/*!
 * @brief This function copies the value in member pose
 * @param _pose New value to be copied in member pose
 */
void Odometry_::pose(
        const geometry_msgs::msg::dds_::PoseWithCovariance_& _pose)
{
    m_pose = _pose;
}

/*!
 * @brief This function moves the value in member pose
 * @param _pose New value to be moved in member pose
 */
void Odometry_::pose(
        geometry_msgs::msg::dds_::PoseWithCovariance_&& _pose)
{
    m_pose = std::move(_pose);
}

/*!
 * @brief This function returns a constant reference to member pose
 * @return Constant reference to member pose
 */
const geometry_msgs::msg::dds_::PoseWithCovariance_& Odometry_::pose() const
{
    return m_pose;
}

/*!
 * @brief This function returns a reference to member pose
 * @return Reference to member pose
 */
geometry_msgs::msg::dds_::PoseWithCovariance_& Odometry_::pose()
{
    return m_pose;
}


/*!
 * @brief This function copies the value in member twist
 * @param _twist New value to be copied in member twist
 */
void Odometry_::twist(
        const geometry_msgs::msg::dds_::TwistWithCovariance_& _twist)
{
    m_twist = _twist;
}

/*!
 * @brief This function moves the value in member twist
 * @param _twist New value to be moved in member twist
 */
void Odometry_::twist(
        geometry_msgs::msg::dds_::TwistWithCovariance_&& _twist)
{
    m_twist = std::move(_twist);
}

/*!
 * @brief This function returns a constant reference to member twist
 * @return Constant reference to member twist
 */
const geometry_msgs::msg::dds_::TwistWithCovariance_& Odometry_::twist() const
{
    return m_twist;
}

/*!
 * @brief This function returns a reference to member twist
 * @return Reference to member twist
 */
geometry_msgs::msg::dds_::TwistWithCovariance_& Odometry_::twist()
{
    return m_twist;
}





} // namespace dds_


} // namespace msg


} // namespace nav_msgs

