// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file Twist.cpp
 * This source file contains the implementation of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "Twist.h"

#include <fastcdr/Cdr.h>


#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

namespace helper { namespace internal {

enum class Size {
    UInt8,
    UInt16,
    UInt32,
    UInt64,
};

constexpr Size get_size(int s) {
    return (s <= 8 ) ? Size::UInt8:
           (s <= 16) ? Size::UInt16:
           (s <= 32) ? Size::UInt32: Size::UInt64;
}

template<Size s>
struct FindTypeH;

template<>
struct FindTypeH<Size::UInt8> {
    using type = std::uint8_t;
};

template<>
struct FindTypeH<Size::UInt16> {
    using type = std::uint16_t;
};

template<>
struct FindTypeH<Size::UInt32> {
    using type = std::uint32_t;
};

template<>
struct FindTypeH<Size::UInt64> {
    using type = std::uint64_t;
};
}

template<int S>
struct FindType {
    using type = typename internal::FindTypeH<internal::get_size(S)>::type;
};
}

#define geometry_msgs_msg_dds__Vector3__max_cdr_typesize 24ULL;
#define geometry_msgs_msg_dds__Twist__max_cdr_typesize 48ULL;


namespace geometry_msgs {

namespace msg {

namespace dds_ {



Twist_::Twist_()
{
    // geometry_msgs::msg::dds_::Vector3_ m_linear

    // geometry_msgs::msg::dds_::Vector3_ m_angular


}

Twist_::~Twist_()
{
}

Twist_::Twist_(
        const Twist_& x)
{
    m_linear = x.m_linear;


    m_angular = x.m_angular;

}

Twist_::Twist_(
        Twist_&& x) noexcept
{
    m_linear = std::move(x.m_linear);


    m_angular = std::move(x.m_angular);

}

Twist_& Twist_::operator =(
        const Twist_& x)
{
    m_linear = x.m_linear;


    m_angular = x.m_angular;

    return *this;
}

Twist_& Twist_::operator =(
        Twist_&& x) noexcept
{
    m_linear = std::move(x.m_linear);


    m_angular = std::move(x.m_angular);

    return *this;
}

bool Twist_::operator ==(
        const Twist_& x) const
{
    return (m_linear == x.m_linear &&
           m_angular == x.m_angular);
}

bool Twist_::operator !=(
        const Twist_& x) const
{
    return !(*this == x);
}

size_t Twist_::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    static_cast<void>(current_alignment);
    return geometry_msgs_msg_dds__Twist__max_cdr_typesize;
}

size_t Twist_::getCdrSerializedSize(
        const Twist_& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;

    current_alignment += geometry_msgs::msg::dds_::Vector3_::getCdrSerializedSize(data.linear(), current_alignment);


    current_alignment += geometry_msgs::msg::dds_::Vector3_::getCdrSerializedSize(data.angular(), current_alignment);


    return current_alignment - initial_alignment;
}


void Twist_::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{
    scdr << m_linear;

    scdr << m_angular;

}

void Twist_::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{
    dcdr >> m_linear;



    dcdr >> m_angular;


}


bool Twist_::isKeyDefined()
{
    return false;
}

void Twist_::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
}

/*!
 * @brief This function copies the value in member linear
 * @param _linear New value to be copied in member linear
 */
void Twist_::linear(
        const geometry_msgs::msg::dds_::Vector3_& _linear)
{
    m_linear = _linear;
}

/*!
 * @brief This function moves the value in member linear
 * @param _linear New value to be moved in member linear
 */
void Twist_::linear(
        geometry_msgs::msg::dds_::Vector3_&& _linear)
{
    m_linear = std::move(_linear);
}

/*!
 * @brief This function returns a constant reference to member linear
 * @return Constant reference to member linear
 */
const geometry_msgs::msg::dds_::Vector3_& Twist_::linear() const
{
    return m_linear;
}

/*!
 * @brief This function returns a reference to member linear
 * @return Reference to member linear
 */
geometry_msgs::msg::dds_::Vector3_& Twist_::linear()
{
    return m_linear;
}


/*!
 * @brief This function copies the value in member angular
 * @param _angular New value to be copied in member angular
 */
void Twist_::angular(
        const geometry_msgs::msg::dds_::Vector3_& _angular)
{
    m_angular = _angular;
}

/*!
 * @brief This function moves the value in member angular
 * @param _angular New value to be moved in member angular
 */
void Twist_::angular(
        geometry_msgs::msg::dds_::Vector3_&& _angular)
{
    m_angular = std::move(_angular);
}

/*!
 * @brief This function returns a constant reference to member angular
 * @return Constant reference to member angular
 */
const geometry_msgs::msg::dds_::Vector3_& Twist_::angular() const
{
    return m_angular;
}

/*!
 * @brief This function returns a reference to member angular
 * @return Reference to member angular
 */
geometry_msgs::msg::dds_::Vector3_& Twist_::angular()
{
    return m_angular;
}





} // namespace dds_


} // namespace msg


} // namespace geometry_msgs

