// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file TwistWithCovariance.cpp
 * This source file contains the implementation of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "TwistWithCovariance.h"

#include <fastcdr/Cdr.h>


#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

namespace helper { namespace internal {

enum class Size {
    UInt8,
    UInt16,
    UInt32,
    UInt64,
};

constexpr Size get_size(int s) {
    return (s <= 8 ) ? Size::UInt8:
           (s <= 16) ? Size::UInt16:
           (s <= 32) ? Size::UInt32: Size::UInt64;
}

template<Size s>
struct FindTypeH;

template<>
struct FindTypeH<Size::UInt8> {
    using type = std::uint8_t;
};

template<>
struct FindTypeH<Size::UInt16> {
    using type = std::uint16_t;
};

template<>
struct FindTypeH<Size::UInt32> {
    using type = std::uint32_t;
};

template<>
struct FindTypeH<Size::UInt64> {
    using type = std::uint64_t;
};
}

template<int S>
struct FindType {
    using type = typename internal::FindTypeH<internal::get_size(S)>::type;
};
}

#define geometry_msgs_msg_dds__Vector3__max_cdr_typesize 24ULL;
#define geometry_msgs_msg_dds__TwistWithCovariance__max_cdr_typesize 336ULL;
#define geometry_msgs_msg_dds__Twist__max_cdr_typesize 48ULL;


namespace geometry_msgs {

namespace msg {

namespace dds_ {



TwistWithCovariance_::TwistWithCovariance_()
{
    // geometry_msgs::msg::dds_::Twist_ m_twist

    // double m_covariance
    memset(&m_covariance, 0, ((36)) * 8);

}

TwistWithCovariance_::~TwistWithCovariance_()
{
}

TwistWithCovariance_::TwistWithCovariance_(
        const TwistWithCovariance_& x)
{
    m_twist = x.m_twist;


    m_covariance = x.m_covariance;

}

TwistWithCovariance_::TwistWithCovariance_(
        TwistWithCovariance_&& x) noexcept
{
    m_twist = std::move(x.m_twist);


    m_covariance = std::move(x.m_covariance);

}

TwistWithCovariance_& TwistWithCovariance_::operator =(
        const TwistWithCovariance_& x)
{
    m_twist = x.m_twist;


    m_covariance = x.m_covariance;

    return *this;
}

TwistWithCovariance_& TwistWithCovariance_::operator =(
        TwistWithCovariance_&& x) noexcept
{
    m_twist = std::move(x.m_twist);


    m_covariance = std::move(x.m_covariance);

    return *this;
}

bool TwistWithCovariance_::operator ==(
        const TwistWithCovariance_& x) const
{
    return (m_twist == x.m_twist &&
           m_covariance == x.m_covariance);
}

bool TwistWithCovariance_::operator !=(
        const TwistWithCovariance_& x) const
{
    return !(*this == x);
}

size_t TwistWithCovariance_::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    static_cast<void>(current_alignment);
    return geometry_msgs_msg_dds__TwistWithCovariance__max_cdr_typesize;
}

size_t TwistWithCovariance_::getCdrSerializedSize(
        const TwistWithCovariance_& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;

    current_alignment += geometry_msgs::msg::dds_::Twist_::getCdrSerializedSize(data.twist(), current_alignment);


    current_alignment += (((36)) * 8) + eprosima::fastcdr::Cdr::alignment(current_alignment, 8);



    return current_alignment - initial_alignment;
}


void TwistWithCovariance_::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{
    scdr << m_twist;

    scdr << m_covariance;


}

void TwistWithCovariance_::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{
    dcdr >> m_twist;



    dcdr >> m_covariance;


}


bool TwistWithCovariance_::isKeyDefined()
{
    return false;
}

void TwistWithCovariance_::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
}

/*!
 * @brief This function copies the value in member twist
 * @param _twist New value to be copied in member twist
 */
void TwistWithCovariance_::twist(
        const geometry_msgs::msg::dds_::Twist_& _twist)
{
    m_twist = _twist;
}

/*!
 * @brief This function moves the value in member twist
 * @param _twist New value to be moved in member twist
 */
void TwistWithCovariance_::twist(
        geometry_msgs::msg::dds_::Twist_&& _twist)
{
    m_twist = std::move(_twist);
}

/*!
 * @brief This function returns a constant reference to member twist
 * @return Constant reference to member twist
 */
const geometry_msgs::msg::dds_::Twist_& TwistWithCovariance_::twist() const
{
    return m_twist;
}

/*!
 * @brief This function returns a reference to member twist
 * @return Reference to member twist
 */
geometry_msgs::msg::dds_::Twist_& TwistWithCovariance_::twist()
{
    return m_twist;
}


/*!
 * @brief This function copies the value in member covariance
 * @param _covariance New value to be copied in member covariance
 */
void TwistWithCovariance_::covariance(
        const std::array<double, 36>& _covariance)
{
    m_covariance = _covariance;
}

/*!
 * @brief This function moves the value in member covariance
 * @param _covariance New value to be moved in member covariance
 */
void TwistWithCovariance_::covariance(
        std::array<double, 36>&& _covariance)
{
    m_covariance = std::move(_covariance);
}

/*!
 * @brief This function returns a constant reference to member covariance
 * @return Constant reference to member covariance
 */
const std::array<double, 36>& TwistWithCovariance_::covariance() const
{
    return m_covariance;
}

/*!
 * @brief This function returns a reference to member covariance
 * @return Reference to member covariance
 */
std::array<double, 36>& TwistWithCovariance_::covariance()
{
    return m_covariance;
}





} // namespace dds_


} // namespace msg


} // namespace geometry_msgs

