// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file Time.cpp
 * This source file contains the implementation of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "Time.h"

#include <fastcdr/Cdr.h>


#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

namespace helper { namespace internal {

enum class Size {
    UInt8,
    UInt16,
    UInt32,
    UInt64,
};

constexpr Size get_size(int s) {
    return (s <= 8 ) ? Size::UInt8:
           (s <= 16) ? Size::UInt16:
           (s <= 32) ? Size::UInt32: Size::UInt64;
}

template<Size s>
struct FindTypeH;

template<>
struct FindTypeH<Size::UInt8> {
    using type = std::uint8_t;
};

template<>
struct FindTypeH<Size::UInt16> {
    using type = std::uint16_t;
};

template<>
struct FindTypeH<Size::UInt32> {
    using type = std::uint32_t;
};

template<>
struct FindTypeH<Size::UInt64> {
    using type = std::uint64_t;
};
}

template<int S>
struct FindType {
    using type = typename internal::FindTypeH<internal::get_size(S)>::type;
};
}

#define builtin_interfaces_msg_dds__Time__max_cdr_typesize 8ULL;


namespace builtin_interfaces {

namespace msg {

namespace dds_ {



Time_::Time_()
{
    // long m_sec
    m_sec = 0;
    // unsigned long m_nanosec
    m_nanosec = 0;

}

Time_::~Time_()
{
}

Time_::Time_(
        const Time_& x)
{
    m_sec = x.m_sec;


    m_nanosec = x.m_nanosec;

}

Time_::Time_(
        Time_&& x) noexcept
{
    m_sec = x.m_sec;


    m_nanosec = x.m_nanosec;

}

Time_& Time_::operator =(
        const Time_& x)
{
    m_sec = x.m_sec;


    m_nanosec = x.m_nanosec;

    return *this;
}

Time_& Time_::operator =(
        Time_&& x) noexcept
{
    m_sec = x.m_sec;


    m_nanosec = x.m_nanosec;

    return *this;
}

bool Time_::operator ==(
        const Time_& x) const
{
    return (m_sec == x.m_sec &&
           m_nanosec == x.m_nanosec);
}

bool Time_::operator !=(
        const Time_& x) const
{
    return !(*this == x);
}

size_t Time_::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    static_cast<void>(current_alignment);
    return builtin_interfaces_msg_dds__Time__max_cdr_typesize;
}

size_t Time_::getCdrSerializedSize(
        const Time_& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;

    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    return current_alignment - initial_alignment;
}


void Time_::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{
    scdr << m_sec;

    scdr << m_nanosec;

}

void Time_::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{
    dcdr >> m_sec;



    dcdr >> m_nanosec;


}


bool Time_::isKeyDefined()
{
    return false;
}

void Time_::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
}

/*!
 * @brief This function sets a value in member sec
 * @param _sec New value for member sec
 */
void Time_::sec(
        int32_t _sec)
{
    m_sec = _sec;
}

/*!
 * @brief This function returns the value of member sec
 * @return Value of member sec
 */
int32_t Time_::sec() const
{
    return m_sec;
}

/*!
 * @brief This function returns a reference to member sec
 * @return Reference to member sec
 */
int32_t& Time_::sec()
{
    return m_sec;
}


/*!
 * @brief This function sets a value in member nanosec
 * @param _nanosec New value for member nanosec
 */
void Time_::nanosec(
        uint32_t _nanosec)
{
    m_nanosec = _nanosec;
}

/*!
 * @brief This function returns the value of member nanosec
 * @return Value of member nanosec
 */
uint32_t Time_::nanosec() const
{
    return m_nanosec;
}

/*!
 * @brief This function returns a reference to member nanosec
 * @return Reference to member nanosec
 */
uint32_t& Time_::nanosec()
{
    return m_nanosec;
}





} // namespace dds_


} // namespace msg


} // namespace builtin_interfaces

