// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file PoseWithCovariance.cpp
 * This source file contains the implementation of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "PoseWithCovariance.h"

#include <fastcdr/Cdr.h>


#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

namespace helper { namespace internal {

enum class Size {
    UInt8,
    UInt16,
    UInt32,
    UInt64,
};

constexpr Size get_size(int s) {
    return (s <= 8 ) ? Size::UInt8:
           (s <= 16) ? Size::UInt16:
           (s <= 32) ? Size::UInt32: Size::UInt64;
}

template<Size s>
struct FindTypeH;

template<>
struct FindTypeH<Size::UInt8> {
    using type = std::uint8_t;
};

template<>
struct FindTypeH<Size::UInt16> {
    using type = std::uint16_t;
};

template<>
struct FindTypeH<Size::UInt32> {
    using type = std::uint32_t;
};

template<>
struct FindTypeH<Size::UInt64> {
    using type = std::uint64_t;
};
}

template<int S>
struct FindType {
    using type = typename internal::FindTypeH<internal::get_size(S)>::type;
};
}

#define geometry_msgs_msg_dds__Quaternion__max_cdr_typesize 32ULL;
#define geometry_msgs_msg_dds__Point__max_cdr_typesize 24ULL;
#define geometry_msgs_msg_dds__Pose__max_cdr_typesize 56ULL;
#define geometry_msgs_msg_dds__PoseWithCovariance__max_cdr_typesize 344ULL;


namespace geometry_msgs {

namespace msg {

namespace dds_ {



PoseWithCovariance_::PoseWithCovariance_()
{
    // geometry_msgs::msg::dds_::Pose_ m_pose

    // double m_covariance
    memset(&m_covariance, 0, ((36)) * 8);

}

PoseWithCovariance_::~PoseWithCovariance_()
{
}

PoseWithCovariance_::PoseWithCovariance_(
        const PoseWithCovariance_& x)
{
    m_pose = x.m_pose;


    m_covariance = x.m_covariance;

}

PoseWithCovariance_::PoseWithCovariance_(
        PoseWithCovariance_&& x) noexcept
{
    m_pose = std::move(x.m_pose);


    m_covariance = std::move(x.m_covariance);

}

PoseWithCovariance_& PoseWithCovariance_::operator =(
        const PoseWithCovariance_& x)
{
    m_pose = x.m_pose;


    m_covariance = x.m_covariance;

    return *this;
}

PoseWithCovariance_& PoseWithCovariance_::operator =(
        PoseWithCovariance_&& x) noexcept
{
    m_pose = std::move(x.m_pose);


    m_covariance = std::move(x.m_covariance);

    return *this;
}

bool PoseWithCovariance_::operator ==(
        const PoseWithCovariance_& x) const
{
    return (m_pose == x.m_pose &&
           m_covariance == x.m_covariance);
}

bool PoseWithCovariance_::operator !=(
        const PoseWithCovariance_& x) const
{
    return !(*this == x);
}

size_t PoseWithCovariance_::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    static_cast<void>(current_alignment);
    return geometry_msgs_msg_dds__PoseWithCovariance__max_cdr_typesize;
}

size_t PoseWithCovariance_::getCdrSerializedSize(
        const PoseWithCovariance_& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;

    current_alignment += geometry_msgs::msg::dds_::Pose_::getCdrSerializedSize(data.pose(), current_alignment);


    current_alignment += (((36)) * 8) + eprosima::fastcdr::Cdr::alignment(current_alignment, 8);



    return current_alignment - initial_alignment;
}


void PoseWithCovariance_::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{
    scdr << m_pose;

    scdr << m_covariance;


}

void PoseWithCovariance_::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{
    dcdr >> m_pose;



    dcdr >> m_covariance;


}


bool PoseWithCovariance_::isKeyDefined()
{
    return false;
}

void PoseWithCovariance_::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
}

/*!
 * @brief This function copies the value in member pose
 * @param _pose New value to be copied in member pose
 */
void PoseWithCovariance_::pose(
        const geometry_msgs::msg::dds_::Pose_& _pose)
{
    m_pose = _pose;
}

/*!
 * @brief This function moves the value in member pose
 * @param _pose New value to be moved in member pose
 */
void PoseWithCovariance_::pose(
        geometry_msgs::msg::dds_::Pose_&& _pose)
{
    m_pose = std::move(_pose);
}

/*!
 * @brief This function returns a constant reference to member pose
 * @return Constant reference to member pose
 */
const geometry_msgs::msg::dds_::Pose_& PoseWithCovariance_::pose() const
{
    return m_pose;
}

/*!
 * @brief This function returns a reference to member pose
 * @return Reference to member pose
 */
geometry_msgs::msg::dds_::Pose_& PoseWithCovariance_::pose()
{
    return m_pose;
}


/*!
 * @brief This function copies the value in member covariance
 * @param _covariance New value to be copied in member covariance
 */
void PoseWithCovariance_::covariance(
        const std::array<double, 36>& _covariance)
{
    m_covariance = _covariance;
}

/*!
 * @brief This function moves the value in member covariance
 * @param _covariance New value to be moved in member covariance
 */
void PoseWithCovariance_::covariance(
        std::array<double, 36>&& _covariance)
{
    m_covariance = std::move(_covariance);
}

/*!
 * @brief This function returns a constant reference to member covariance
 * @return Constant reference to member covariance
 */
const std::array<double, 36>& PoseWithCovariance_::covariance() const
{
    return m_covariance;
}

/*!
 * @brief This function returns a reference to member covariance
 * @return Reference to member covariance
 */
std::array<double, 36>& PoseWithCovariance_::covariance()
{
    return m_covariance;
}





} // namespace dds_


} // namespace msg


} // namespace geometry_msgs

