// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file Pose.cpp
 * This source file contains the implementation of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "Pose.h"

#include <fastcdr/Cdr.h>


#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

namespace helper { namespace internal {

enum class Size {
    UInt8,
    UInt16,
    UInt32,
    UInt64,
};

constexpr Size get_size(int s) {
    return (s <= 8 ) ? Size::UInt8:
           (s <= 16) ? Size::UInt16:
           (s <= 32) ? Size::UInt32: Size::UInt64;
}

template<Size s>
struct FindTypeH;

template<>
struct FindTypeH<Size::UInt8> {
    using type = std::uint8_t;
};

template<>
struct FindTypeH<Size::UInt16> {
    using type = std::uint16_t;
};

template<>
struct FindTypeH<Size::UInt32> {
    using type = std::uint32_t;
};

template<>
struct FindTypeH<Size::UInt64> {
    using type = std::uint64_t;
};
}

template<int S>
struct FindType {
    using type = typename internal::FindTypeH<internal::get_size(S)>::type;
};
}

#define geometry_msgs_msg_dds__Quaternion__max_cdr_typesize 32ULL;
#define geometry_msgs_msg_dds__Point__max_cdr_typesize 24ULL;
#define geometry_msgs_msg_dds__Pose__max_cdr_typesize 56ULL;


namespace geometry_msgs {

namespace msg {

namespace dds_ {



Pose_::Pose_()
{
    // geometry_msgs::msg::dds_::Point_ m_position

    // geometry_msgs::msg::dds_::Quaternion_ m_orientation


}

Pose_::~Pose_()
{
}

Pose_::Pose_(
        const Pose_& x)
{
    m_position = x.m_position;


    m_orientation = x.m_orientation;

}

Pose_::Pose_(
        Pose_&& x) noexcept
{
    m_position = std::move(x.m_position);


    m_orientation = std::move(x.m_orientation);

}

Pose_& Pose_::operator =(
        const Pose_& x)
{
    m_position = x.m_position;


    m_orientation = x.m_orientation;

    return *this;
}

Pose_& Pose_::operator =(
        Pose_&& x) noexcept
{
    m_position = std::move(x.m_position);


    m_orientation = std::move(x.m_orientation);

    return *this;
}

bool Pose_::operator ==(
        const Pose_& x) const
{
    return (m_position == x.m_position &&
           m_orientation == x.m_orientation);
}

bool Pose_::operator !=(
        const Pose_& x) const
{
    return !(*this == x);
}

size_t Pose_::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    static_cast<void>(current_alignment);
    return geometry_msgs_msg_dds__Pose__max_cdr_typesize;
}

size_t Pose_::getCdrSerializedSize(
        const Pose_& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;

    current_alignment += geometry_msgs::msg::dds_::Point_::getCdrSerializedSize(data.position(), current_alignment);


    current_alignment += geometry_msgs::msg::dds_::Quaternion_::getCdrSerializedSize(data.orientation(), current_alignment);


    return current_alignment - initial_alignment;
}


void Pose_::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{
    scdr << m_position;

    scdr << m_orientation;

}

void Pose_::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{
    dcdr >> m_position;



    dcdr >> m_orientation;


}


bool Pose_::isKeyDefined()
{
    return false;
}

void Pose_::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
}

/*!
 * @brief This function copies the value in member position
 * @param _position New value to be copied in member position
 */
void Pose_::position(
        const geometry_msgs::msg::dds_::Point_& _position)
{
    m_position = _position;
}

/*!
 * @brief This function moves the value in member position
 * @param _position New value to be moved in member position
 */
void Pose_::position(
        geometry_msgs::msg::dds_::Point_&& _position)
{
    m_position = std::move(_position);
}

/*!
 * @brief This function returns a constant reference to member position
 * @return Constant reference to member position
 */
const geometry_msgs::msg::dds_::Point_& Pose_::position() const
{
    return m_position;
}

/*!
 * @brief This function returns a reference to member position
 * @return Reference to member position
 */
geometry_msgs::msg::dds_::Point_& Pose_::position()
{
    return m_position;
}


/*!
 * @brief This function copies the value in member orientation
 * @param _orientation New value to be copied in member orientation
 */
void Pose_::orientation(
        const geometry_msgs::msg::dds_::Quaternion_& _orientation)
{
    m_orientation = _orientation;
}

/*!
 * @brief This function moves the value in member orientation
 * @param _orientation New value to be moved in member orientation
 */
void Pose_::orientation(
        geometry_msgs::msg::dds_::Quaternion_&& _orientation)
{
    m_orientation = std::move(_orientation);
}

/*!
 * @brief This function returns a constant reference to member orientation
 * @return Constant reference to member orientation
 */
const geometry_msgs::msg::dds_::Quaternion_& Pose_::orientation() const
{
    return m_orientation;
}

/*!
 * @brief This function returns a reference to member orientation
 * @return Reference to member orientation
 */
geometry_msgs::msg::dds_::Quaternion_& Pose_::orientation()
{
    return m_orientation;
}





} // namespace dds_


} // namespace msg


} // namespace geometry_msgs

