// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file Vector3.cpp
 * This source file contains the implementation of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "Vector3.h"

#include <fastcdr/Cdr.h>


#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

namespace helper { namespace internal {

enum class Size {
    UInt8,
    UInt16,
    UInt32,
    UInt64,
};

constexpr Size get_size(int s) {
    return (s <= 8 ) ? Size::UInt8:
           (s <= 16) ? Size::UInt16:
           (s <= 32) ? Size::UInt32: Size::UInt64;
}

template<Size s>
struct FindTypeH;

template<>
struct FindTypeH<Size::UInt8> {
    using type = std::uint8_t;
};

template<>
struct FindTypeH<Size::UInt16> {
    using type = std::uint16_t;
};

template<>
struct FindTypeH<Size::UInt32> {
    using type = std::uint32_t;
};

template<>
struct FindTypeH<Size::UInt64> {
    using type = std::uint64_t;
};
}

template<int S>
struct FindType {
    using type = typename internal::FindTypeH<internal::get_size(S)>::type;
};
}

#define geometry_msgs_msg_dds__Vector3__max_cdr_typesize 24ULL;


namespace geometry_msgs {

namespace msg {

namespace dds_ {



Vector3_::Vector3_()
{
    // double m_x
    m_x = 0.0;
    // double m_y
    m_y = 0.0;
    // double m_z
    m_z = 0.0;

}

Vector3_::~Vector3_()
{
}

Vector3_::Vector3_(
        const Vector3_& x)
{
    m_x = x.m_x;


    m_y = x.m_y;


    m_z = x.m_z;

}

Vector3_::Vector3_(
        Vector3_&& x) noexcept
{
    m_x = x.m_x;


    m_y = x.m_y;


    m_z = x.m_z;

}

Vector3_& Vector3_::operator =(
        const Vector3_& x)
{
    m_x = x.m_x;


    m_y = x.m_y;


    m_z = x.m_z;

    return *this;
}

Vector3_& Vector3_::operator =(
        Vector3_&& x) noexcept
{
    m_x = x.m_x;


    m_y = x.m_y;


    m_z = x.m_z;

    return *this;
}

bool Vector3_::operator ==(
        const Vector3_& x) const
{
    return (m_x == x.m_x &&
           m_y == x.m_y &&
           m_z == x.m_z);
}

bool Vector3_::operator !=(
        const Vector3_& x) const
{
    return !(*this == x);
}

size_t Vector3_::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    static_cast<void>(current_alignment);
    return geometry_msgs_msg_dds__Vector3__max_cdr_typesize;
}

size_t Vector3_::getCdrSerializedSize(
        const Vector3_& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;

    current_alignment += 8 + eprosima::fastcdr::Cdr::alignment(current_alignment, 8);


    current_alignment += 8 + eprosima::fastcdr::Cdr::alignment(current_alignment, 8);


    current_alignment += 8 + eprosima::fastcdr::Cdr::alignment(current_alignment, 8);


    return current_alignment - initial_alignment;
}


void Vector3_::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{
    scdr << m_x;

    scdr << m_y;

    scdr << m_z;

}

void Vector3_::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{
    dcdr >> m_x;



    dcdr >> m_y;



    dcdr >> m_z;


}


bool Vector3_::isKeyDefined()
{
    return false;
}

void Vector3_::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
}

/*!
 * @brief This function sets a value in member x
 * @param _x New value for member x
 */
void Vector3_::x(
        double _x)
{
    m_x = _x;
}

/*!
 * @brief This function returns the value of member x
 * @return Value of member x
 */
double Vector3_::x() const
{
    return m_x;
}

/*!
 * @brief This function returns a reference to member x
 * @return Reference to member x
 */
double& Vector3_::x()
{
    return m_x;
}


/*!
 * @brief This function sets a value in member y
 * @param _y New value for member y
 */
void Vector3_::y(
        double _y)
{
    m_y = _y;
}

/*!
 * @brief This function returns the value of member y
 * @return Value of member y
 */
double Vector3_::y() const
{
    return m_y;
}

/*!
 * @brief This function returns a reference to member y
 * @return Reference to member y
 */
double& Vector3_::y()
{
    return m_y;
}


/*!
 * @brief This function sets a value in member z
 * @param _z New value for member z
 */
void Vector3_::z(
        double _z)
{
    m_z = _z;
}

/*!
 * @brief This function returns the value of member z
 * @return Value of member z
 */
double Vector3_::z() const
{
    return m_z;
}

/*!
 * @brief This function returns a reference to member z
 * @return Reference to member z
 */
double& Vector3_::z()
{
    return m_z;
}





} // namespace dds_


} // namespace msg


} // namespace geometry_msgs

