// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file BatteryState.cpp
 * This source file contains the implementation of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "BatteryState.h"

#include <fastcdr/Cdr.h>


#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

namespace helper { namespace internal {

enum class Size {
    UInt8,
    UInt16,
    UInt32,
    UInt64,
};

constexpr Size get_size(int s) {
    return (s <= 8 ) ? Size::UInt8:
           (s <= 16) ? Size::UInt16:
           (s <= 32) ? Size::UInt32: Size::UInt64;
}

template<Size s>
struct FindTypeH;

template<>
struct FindTypeH<Size::UInt8> {
    using type = std::uint8_t;
};

template<>
struct FindTypeH<Size::UInt16> {
    using type = std::uint16_t;
};

template<>
struct FindTypeH<Size::UInt32> {
    using type = std::uint32_t;
};

template<>
struct FindTypeH<Size::UInt64> {
    using type = std::uint64_t;
};
}

template<int S>
struct FindType {
    using type = typename internal::FindTypeH<internal::get_size(S)>::type;
};
}

#define booster_interface_msg_dds__BatteryState__max_cdr_typesize 16ULL;


namespace booster_interface {

namespace msg {

namespace dds_ {



BatteryState_::BatteryState_()
{
    // float m_voltage
    m_voltage = 0.0;
    // float m_current
    m_current = 0.0;
    // float m_soc
    m_soc = 0.0;
    // float m_average_voltage
    m_average_voltage = 0.0;

}

BatteryState_::~BatteryState_()
{
}

BatteryState_::BatteryState_(
        const BatteryState_& x)
{
    m_voltage = x.m_voltage;


    m_current = x.m_current;


    m_soc = x.m_soc;


    m_average_voltage = x.m_average_voltage;

}

BatteryState_::BatteryState_(
        BatteryState_&& x) noexcept
{
    m_voltage = x.m_voltage;


    m_current = x.m_current;


    m_soc = x.m_soc;


    m_average_voltage = x.m_average_voltage;

}

BatteryState_& BatteryState_::operator =(
        const BatteryState_& x)
{
    m_voltage = x.m_voltage;


    m_current = x.m_current;


    m_soc = x.m_soc;


    m_average_voltage = x.m_average_voltage;

    return *this;
}

BatteryState_& BatteryState_::operator =(
        BatteryState_&& x) noexcept
{
    m_voltage = x.m_voltage;


    m_current = x.m_current;


    m_soc = x.m_soc;


    m_average_voltage = x.m_average_voltage;

    return *this;
}

bool BatteryState_::operator ==(
        const BatteryState_& x) const
{
    return (m_voltage == x.m_voltage &&
           m_current == x.m_current &&
           m_soc == x.m_soc &&
           m_average_voltage == x.m_average_voltage);
}

bool BatteryState_::operator !=(
        const BatteryState_& x) const
{
    return !(*this == x);
}

size_t BatteryState_::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    static_cast<void>(current_alignment);
    return booster_interface_msg_dds__BatteryState__max_cdr_typesize;
}

size_t BatteryState_::getCdrSerializedSize(
        const BatteryState_& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;

    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    return current_alignment - initial_alignment;
}


void BatteryState_::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{
    scdr << m_voltage;

    scdr << m_current;

    scdr << m_soc;

    scdr << m_average_voltage;

}

void BatteryState_::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{
    dcdr >> m_voltage;



    dcdr >> m_current;



    dcdr >> m_soc;



    dcdr >> m_average_voltage;


}


bool BatteryState_::isKeyDefined()
{
    return false;
}

void BatteryState_::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
}

/*!
 * @brief This function sets a value in member voltage
 * @param _voltage New value for member voltage
 */
void BatteryState_::voltage(
        float _voltage)
{
    m_voltage = _voltage;
}

/*!
 * @brief This function returns the value of member voltage
 * @return Value of member voltage
 */
float BatteryState_::voltage() const
{
    return m_voltage;
}

/*!
 * @brief This function returns a reference to member voltage
 * @return Reference to member voltage
 */
float& BatteryState_::voltage()
{
    return m_voltage;
}


/*!
 * @brief This function sets a value in member current
 * @param _current New value for member current
 */
void BatteryState_::current(
        float _current)
{
    m_current = _current;
}

/*!
 * @brief This function returns the value of member current
 * @return Value of member current
 */
float BatteryState_::current() const
{
    return m_current;
}

/*!
 * @brief This function returns a reference to member current
 * @return Reference to member current
 */
float& BatteryState_::current()
{
    return m_current;
}


/*!
 * @brief This function sets a value in member soc
 * @param _soc New value for member soc
 */
void BatteryState_::soc(
        float _soc)
{
    m_soc = _soc;
}

/*!
 * @brief This function returns the value of member soc
 * @return Value of member soc
 */
float BatteryState_::soc() const
{
    return m_soc;
}

/*!
 * @brief This function returns a reference to member soc
 * @return Reference to member soc
 */
float& BatteryState_::soc()
{
    return m_soc;
}


/*!
 * @brief This function sets a value in member average_voltage
 * @param _average_voltage New value for member average_voltage
 */
void BatteryState_::average_voltage(
        float _average_voltage)
{
    m_average_voltage = _average_voltage;
}

/*!
 * @brief This function returns the value of member average_voltage
 * @return Value of member average_voltage
 */
float BatteryState_::average_voltage() const
{
    return m_average_voltage;
}

/*!
 * @brief This function returns a reference to member average_voltage
 * @return Reference to member average_voltage
 */
float& BatteryState_::average_voltage()
{
    return m_average_voltage;
}





} // namespace dds_


} // namespace msg


} // namespace booster_interface

