// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file BatteryState.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef _FAST_DDS_GENERATED_BOOSTER_INTERFACE_MSG_DDS__BATTERYSTATE_H_
#define _FAST_DDS_GENERATED_BOOSTER_INTERFACE_MSG_DDS__BATTERYSTATE_H_


#include <fastrtps/utils/fixed_size_string.hpp>

#include <stdint.h>
#include <array>
#include <string>
#include <vector>
#include <map>
#include <bitset>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(BATTERYSTATE_SOURCE)
#define BATTERYSTATE_DllAPI __declspec( dllexport )
#else
#define BATTERYSTATE_DllAPI __declspec( dllimport )
#endif // BATTERYSTATE_SOURCE
#else
#define BATTERYSTATE_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define BATTERYSTATE_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
} // namespace fastcdr
} // namespace eprosima



namespace booster_interface {
    namespace msg {
        namespace dds_ {


            /*!
             * @brief This class represents the structure BatteryState_ defined by the user in the IDL file.
             * @ingroup BatteryState
             */
            class BatteryState_
            {
            public:

                /*!
                 * @brief Default constructor.
                 */
                eProsima_user_DllExport BatteryState_();

                /*!
                 * @brief Default destructor.
                 */
                eProsima_user_DllExport ~BatteryState_();

                /*!
                 * @brief Copy constructor.
                 * @param x Reference to the object booster_interface::msg::dds_::BatteryState_ that will be copied.
                 */
                eProsima_user_DllExport BatteryState_(
                        const BatteryState_& x);

                /*!
                 * @brief Move constructor.
                 * @param x Reference to the object booster_interface::msg::dds_::BatteryState_ that will be copied.
                 */
                eProsima_user_DllExport BatteryState_(
                        BatteryState_&& x) noexcept;

                /*!
                 * @brief Copy assignment.
                 * @param x Reference to the object booster_interface::msg::dds_::BatteryState_ that will be copied.
                 */
                eProsima_user_DllExport BatteryState_& operator =(
                        const BatteryState_& x);

                /*!
                 * @brief Move assignment.
                 * @param x Reference to the object booster_interface::msg::dds_::BatteryState_ that will be copied.
                 */
                eProsima_user_DllExport BatteryState_& operator =(
                        BatteryState_&& x) noexcept;

                /*!
                 * @brief Comparison operator.
                 * @param x booster_interface::msg::dds_::BatteryState_ object to compare.
                 */
                eProsima_user_DllExport bool operator ==(
                        const BatteryState_& x) const;

                /*!
                 * @brief Comparison operator.
                 * @param x booster_interface::msg::dds_::BatteryState_ object to compare.
                 */
                eProsima_user_DllExport bool operator !=(
                        const BatteryState_& x) const;

                /*!
                 * @brief This function sets a value in member voltage
                 * @param _voltage New value for member voltage
                 */
                eProsima_user_DllExport void voltage(
                        float _voltage);

                /*!
                 * @brief This function returns the value of member voltage
                 * @return Value of member voltage
                 */
                eProsima_user_DllExport float voltage() const;

                /*!
                 * @brief This function returns a reference to member voltage
                 * @return Reference to member voltage
                 */
                eProsima_user_DllExport float& voltage();


                /*!
                 * @brief This function sets a value in member current
                 * @param _current New value for member current
                 */
                eProsima_user_DllExport void current(
                        float _current);

                /*!
                 * @brief This function returns the value of member current
                 * @return Value of member current
                 */
                eProsima_user_DllExport float current() const;

                /*!
                 * @brief This function returns a reference to member current
                 * @return Reference to member current
                 */
                eProsima_user_DllExport float& current();


                /*!
                 * @brief This function sets a value in member soc
                 * @param _soc New value for member soc
                 */
                eProsima_user_DllExport void soc(
                        float _soc);

                /*!
                 * @brief This function returns the value of member soc
                 * @return Value of member soc
                 */
                eProsima_user_DllExport float soc() const;

                /*!
                 * @brief This function returns a reference to member soc
                 * @return Reference to member soc
                 */
                eProsima_user_DllExport float& soc();


                /*!
                 * @brief This function sets a value in member average_voltage
                 * @param _average_voltage New value for member average_voltage
                 */
                eProsima_user_DllExport void average_voltage(
                        float _average_voltage);

                /*!
                 * @brief This function returns the value of member average_voltage
                 * @return Value of member average_voltage
                 */
                eProsima_user_DllExport float average_voltage() const;

                /*!
                 * @brief This function returns a reference to member average_voltage
                 * @return Reference to member average_voltage
                 */
                eProsima_user_DllExport float& average_voltage();


                /*!
                * @brief This function returns the maximum serialized size of an object
                * depending on the buffer alignment.
                * @param current_alignment Buffer alignment.
                * @return Maximum serialized size.
                */
                eProsima_user_DllExport static size_t getMaxCdrSerializedSize(
                        size_t current_alignment = 0);

                /*!
                 * @brief This function returns the serialized size of a data depending on the buffer alignment.
                 * @param data Data which is calculated its serialized size.
                 * @param current_alignment Buffer alignment.
                 * @return Serialized size.
                 */
                eProsima_user_DllExport static size_t getCdrSerializedSize(
                        const booster_interface::msg::dds_::BatteryState_& data,
                        size_t current_alignment = 0);



                /*!
                 * @brief This function serializes an object using CDR serialization.
                 * @param cdr CDR serialization object.
                 */
                eProsima_user_DllExport void serialize(
                        eprosima::fastcdr::Cdr& cdr) const;

                /*!
                 * @brief This function deserializes an object using CDR serialization.
                 * @param cdr CDR serialization object.
                 */
                eProsima_user_DllExport void deserialize(
                        eprosima::fastcdr::Cdr& cdr);




                /*!
                * @brief This function tells you if the Key has been defined for this type
                */
                eProsima_user_DllExport static bool isKeyDefined();

                /*!
                * @brief This function serializes the key members of an object using CDR serialization.
                * @param cdr CDR serialization object.
                */
                eProsima_user_DllExport void serializeKey(
                        eprosima::fastcdr::Cdr& cdr) const;


            private:

                float m_voltage;
                float m_current;
                float m_soc;
                float m_average_voltage;

            };

        } // namespace dds_
    } // namespace msg
} // namespace booster_interface

#endif // _FAST_DDS_GENERATED_BOOSTER_INTERFACE_MSG_DDS__BATTERYSTATE_H_



