// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file ButtonEvent.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef _FAST_DDS_GENERATED_BOOSTER_INTERFACE_MSG_DDS__BUTTONEVENT_H_
#define _FAST_DDS_GENERATED_BOOSTER_INTERFACE_MSG_DDS__BUTTONEVENT_H_


#include <fastrtps/utils/fixed_size_string.hpp>

#include <stdint.h>
#include <array>
#include <string>
#include <vector>
#include <map>
#include <bitset>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(BUTTONEVENT_SOURCE)
#define BUTTONEVENT_DllAPI __declspec( dllexport )
#else
#define BUTTONEVENT_DllAPI __declspec( dllimport )
#endif // BUTTONEVENT_SOURCE
#else
#define BUTTONEVENT_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define BUTTONEVENT_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
} // namespace fastcdr
} // namespace eprosima



namespace booster_interface {
    namespace msg {
        namespace dds_ {
            /*!
             * @brief This class represents the enumeration ButtonEventType_ defined by the user in the IDL file.
             * @ingroup ButtonEvent
             */
            enum ButtonEventType_ : uint32_t
            {
                PRESS_DOWN,
                PRESS_UP,
                SINGLE_CLICK,
                DOUBLE_CLICK,
                TRIPLE_CLICK,
                LONG_PRESS_START,
                LONG_PRESS_HOLD,
                LONG_PRESS_END
            };


            /*!
             * @brief This class represents the structure ButtonEventMsg_ defined by the user in the IDL file.
             * @ingroup ButtonEvent
             */
            class ButtonEventMsg_
            {
            public:

                /*!
                 * @brief Default constructor.
                 */
                eProsima_user_DllExport ButtonEventMsg_();

                /*!
                 * @brief Default destructor.
                 */
                eProsima_user_DllExport ~ButtonEventMsg_();

                /*!
                 * @brief Copy constructor.
                 * @param x Reference to the object booster_interface::msg::dds_::ButtonEventMsg_ that will be copied.
                 */
                eProsima_user_DllExport ButtonEventMsg_(
                        const ButtonEventMsg_& x);

                /*!
                 * @brief Move constructor.
                 * @param x Reference to the object booster_interface::msg::dds_::ButtonEventMsg_ that will be copied.
                 */
                eProsima_user_DllExport ButtonEventMsg_(
                        ButtonEventMsg_&& x) noexcept;

                /*!
                 * @brief Copy assignment.
                 * @param x Reference to the object booster_interface::msg::dds_::ButtonEventMsg_ that will be copied.
                 */
                eProsima_user_DllExport ButtonEventMsg_& operator =(
                        const ButtonEventMsg_& x);

                /*!
                 * @brief Move assignment.
                 * @param x Reference to the object booster_interface::msg::dds_::ButtonEventMsg_ that will be copied.
                 */
                eProsima_user_DllExport ButtonEventMsg_& operator =(
                        ButtonEventMsg_&& x) noexcept;

                /*!
                 * @brief Comparison operator.
                 * @param x booster_interface::msg::dds_::ButtonEventMsg_ object to compare.
                 */
                eProsima_user_DllExport bool operator ==(
                        const ButtonEventMsg_& x) const;

                /*!
                 * @brief Comparison operator.
                 * @param x booster_interface::msg::dds_::ButtonEventMsg_ object to compare.
                 */
                eProsima_user_DllExport bool operator !=(
                        const ButtonEventMsg_& x) const;

                /*!
                 * @brief This function sets a value in member button
                 * @param _button New value for member button
                 */
                eProsima_user_DllExport void button(
                        int32_t _button);

                /*!
                 * @brief This function returns the value of member button
                 * @return Value of member button
                 */
                eProsima_user_DllExport int32_t button() const;

                /*!
                 * @brief This function returns a reference to member button
                 * @return Reference to member button
                 */
                eProsima_user_DllExport int32_t& button();


                /*!
                 * @brief This function sets a value in member event
                 * @param _event New value for member event
                 */
                eProsima_user_DllExport void event(
                        booster_interface::msg::dds_::ButtonEventType_ _event);

                /*!
                 * @brief This function returns the value of member event
                 * @return Value of member event
                 */
                eProsima_user_DllExport booster_interface::msg::dds_::ButtonEventType_ event() const;

                /*!
                 * @brief This function returns a reference to member event
                 * @return Reference to member event
                 */
                eProsima_user_DllExport booster_interface::msg::dds_::ButtonEventType_& event();


                /*!
                * @brief This function returns the maximum serialized size of an object
                * depending on the buffer alignment.
                * @param current_alignment Buffer alignment.
                * @return Maximum serialized size.
                */
                eProsima_user_DllExport static size_t getMaxCdrSerializedSize(
                        size_t current_alignment = 0);

                /*!
                 * @brief This function returns the serialized size of a data depending on the buffer alignment.
                 * @param data Data which is calculated its serialized size.
                 * @param current_alignment Buffer alignment.
                 * @return Serialized size.
                 */
                eProsima_user_DllExport static size_t getCdrSerializedSize(
                        const booster_interface::msg::dds_::ButtonEventMsg_& data,
                        size_t current_alignment = 0);



                /*!
                 * @brief This function serializes an object using CDR serialization.
                 * @param cdr CDR serialization object.
                 */
                eProsima_user_DllExport void serialize(
                        eprosima::fastcdr::Cdr& cdr) const;

                /*!
                 * @brief This function deserializes an object using CDR serialization.
                 * @param cdr CDR serialization object.
                 */
                eProsima_user_DllExport void deserialize(
                        eprosima::fastcdr::Cdr& cdr);




                /*!
                * @brief This function tells you if the Key has been defined for this type
                */
                eProsima_user_DllExport static bool isKeyDefined();

                /*!
                * @brief This function serializes the key members of an object using CDR serialization.
                * @param cdr CDR serialization object.
                */
                eProsima_user_DllExport void serializeKey(
                        eprosima::fastcdr::Cdr& cdr) const;


            private:

                int32_t m_button;
                booster_interface::msg::dds_::ButtonEventType_ m_event;

            };

        } // namespace dds_
    } // namespace msg
} // namespace booster_interface

#endif // _FAST_DDS_GENERATED_BOOSTER_INTERFACE_MSG_DDS__BUTTONEVENT_H_



