// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file ButtonEvent.cpp
 * This source file contains the implementation of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "ButtonEvent.h"

#include <fastcdr/Cdr.h>


#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

namespace helper { namespace internal {

enum class Size {
    UInt8,
    UInt16,
    UInt32,
    UInt64,
};

constexpr Size get_size(int s) {
    return (s <= 8 ) ? Size::UInt8:
           (s <= 16) ? Size::UInt16:
           (s <= 32) ? Size::UInt32: Size::UInt64;
}

template<Size s>
struct FindTypeH;

template<>
struct FindTypeH<Size::UInt8> {
    using type = std::uint8_t;
};

template<>
struct FindTypeH<Size::UInt16> {
    using type = std::uint16_t;
};

template<>
struct FindTypeH<Size::UInt32> {
    using type = std::uint32_t;
};

template<>
struct FindTypeH<Size::UInt64> {
    using type = std::uint64_t;
};
}

template<int S>
struct FindType {
    using type = typename internal::FindTypeH<internal::get_size(S)>::type;
};
}

#define booster_interface_msg_dds__ButtonEventMsg__max_cdr_typesize 8ULL;



namespace booster_interface {

namespace msg {

namespace dds_ {



ButtonEventMsg_::ButtonEventMsg_()
{
    // long m_button
    m_button = 0;
    // booster_interface::msg::dds_::ButtonEventType_ m_event
    m_event = booster_interface::msg::dds_::PRESS_DOWN;

}

ButtonEventMsg_::~ButtonEventMsg_()
{
}

ButtonEventMsg_::ButtonEventMsg_(
        const ButtonEventMsg_& x)
{
    m_button = x.m_button;


    m_event = x.m_event;

}

ButtonEventMsg_::ButtonEventMsg_(
        ButtonEventMsg_&& x) noexcept
{
    m_button = x.m_button;


    m_event = x.m_event;

}

ButtonEventMsg_& ButtonEventMsg_::operator =(
        const ButtonEventMsg_& x)
{
    m_button = x.m_button;


    m_event = x.m_event;

    return *this;
}

ButtonEventMsg_& ButtonEventMsg_::operator =(
        ButtonEventMsg_&& x) noexcept
{
    m_button = x.m_button;


    m_event = x.m_event;

    return *this;
}

bool ButtonEventMsg_::operator ==(
        const ButtonEventMsg_& x) const
{
    return (m_button == x.m_button &&
           m_event == x.m_event);
}

bool ButtonEventMsg_::operator !=(
        const ButtonEventMsg_& x) const
{
    return !(*this == x);
}

size_t ButtonEventMsg_::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    static_cast<void>(current_alignment);
    return booster_interface_msg_dds__ButtonEventMsg__max_cdr_typesize;
}

size_t ButtonEventMsg_::getCdrSerializedSize(
        const ButtonEventMsg_& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;

    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    return current_alignment - initial_alignment;
}


void ButtonEventMsg_::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{
    scdr << m_button;

    scdr << (uint32_t)m_event;

}

void ButtonEventMsg_::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{
    dcdr >> m_button;



    {
        uint32_t enum_value = 0;
        dcdr >> enum_value;
        m_event = (booster_interface::msg::dds_::ButtonEventType_)enum_value;
    }


}


bool ButtonEventMsg_::isKeyDefined()
{
    return false;
}

void ButtonEventMsg_::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
}

/*!
 * @brief This function sets a value in member button
 * @param _button New value for member button
 */
void ButtonEventMsg_::button(
        int32_t _button)
{
    m_button = _button;
}

/*!
 * @brief This function returns the value of member button
 * @return Value of member button
 */
int32_t ButtonEventMsg_::button() const
{
    return m_button;
}

/*!
 * @brief This function returns a reference to member button
 * @return Reference to member button
 */
int32_t& ButtonEventMsg_::button()
{
    return m_button;
}


/*!
 * @brief This function sets a value in member event
 * @param _event New value for member event
 */
void ButtonEventMsg_::event(
        booster_interface::msg::dds_::ButtonEventType_ _event)
{
    m_event = _event;
}

/*!
 * @brief This function returns the value of member event
 * @return Value of member event
 */
booster_interface::msg::dds_::ButtonEventType_ ButtonEventMsg_::event() const
{
    return m_event;
}

/*!
 * @brief This function returns a reference to member event
 * @return Reference to member event
 */
booster_interface::msg::dds_::ButtonEventType_& ButtonEventMsg_::event()
{
    return m_event;
}





} // namespace dds_


} // namespace msg


} // namespace booster_interface

