// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file FallDownState.cpp
 * This source file contains the implementation of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "FallDownState.h"

#include <fastcdr/Cdr.h>


#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

namespace helper { namespace internal {

enum class Size {
    UInt8,
    UInt16,
    UInt32,
    UInt64,
};

constexpr Size get_size(int s) {
    return (s <= 8 ) ? Size::UInt8:
           (s <= 16) ? Size::UInt16:
           (s <= 32) ? Size::UInt32: Size::UInt64;
}

template<Size s>
struct FindTypeH;

template<>
struct FindTypeH<Size::UInt8> {
    using type = std::uint8_t;
};

template<>
struct FindTypeH<Size::UInt16> {
    using type = std::uint16_t;
};

template<>
struct FindTypeH<Size::UInt32> {
    using type = std::uint32_t;
};

template<>
struct FindTypeH<Size::UInt64> {
    using type = std::uint64_t;
};
}

template<int S>
struct FindType {
    using type = typename internal::FindTypeH<internal::get_size(S)>::type;
};
}

#define booster_interface_msg_dds__FallDownState__max_cdr_typesize 5ULL;


namespace booster_interface {

namespace msg {

namespace dds_ {



FallDownState_::FallDownState_()
{
    // booster_interface::msg::dds_::FallDownStateType_ m_fall_down_state
    m_fall_down_state = booster_interface::msg::dds_::IS_READY;
    // boolean m_is_recovery_available
    m_is_recovery_available = false;

}

FallDownState_::~FallDownState_()
{
}

FallDownState_::FallDownState_(
        const FallDownState_& x)
{
    m_fall_down_state = x.m_fall_down_state;


    m_is_recovery_available = x.m_is_recovery_available;

}

FallDownState_::FallDownState_(
        FallDownState_&& x) noexcept
{
    m_fall_down_state = x.m_fall_down_state;


    m_is_recovery_available = x.m_is_recovery_available;

}

FallDownState_& FallDownState_::operator =(
        const FallDownState_& x)
{
    m_fall_down_state = x.m_fall_down_state;


    m_is_recovery_available = x.m_is_recovery_available;

    return *this;
}

FallDownState_& FallDownState_::operator =(
        FallDownState_&& x) noexcept
{
    m_fall_down_state = x.m_fall_down_state;


    m_is_recovery_available = x.m_is_recovery_available;

    return *this;
}

bool FallDownState_::operator ==(
        const FallDownState_& x) const
{
    return (m_fall_down_state == x.m_fall_down_state &&
           m_is_recovery_available == x.m_is_recovery_available);
}

bool FallDownState_::operator !=(
        const FallDownState_& x) const
{
    return !(*this == x);
}

size_t FallDownState_::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    static_cast<void>(current_alignment);
    return booster_interface_msg_dds__FallDownState__max_cdr_typesize;
}

size_t FallDownState_::getCdrSerializedSize(
        const FallDownState_& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;

    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 1 + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);


    return current_alignment - initial_alignment;
}


void FallDownState_::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{
    scdr << (uint32_t)m_fall_down_state;

    scdr << m_is_recovery_available;

}

void FallDownState_::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{
    {
        uint32_t enum_value = 0;
        dcdr >> enum_value;
        m_fall_down_state = (booster_interface::msg::dds_::FallDownStateType_)enum_value;
    }



    dcdr >> m_is_recovery_available;


}


bool FallDownState_::isKeyDefined()
{
    return false;
}

void FallDownState_::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
}

/*!
 * @brief This function sets a value in member fall_down_state
 * @param _fall_down_state New value for member fall_down_state
 */
void FallDownState_::fall_down_state(
        booster_interface::msg::dds_::FallDownStateType_ _fall_down_state)
{
    m_fall_down_state = _fall_down_state;
}

/*!
 * @brief This function returns the value of member fall_down_state
 * @return Value of member fall_down_state
 */
booster_interface::msg::dds_::FallDownStateType_ FallDownState_::fall_down_state() const
{
    return m_fall_down_state;
}

/*!
 * @brief This function returns a reference to member fall_down_state
 * @return Reference to member fall_down_state
 */
booster_interface::msg::dds_::FallDownStateType_& FallDownState_::fall_down_state()
{
    return m_fall_down_state;
}


/*!
 * @brief This function sets a value in member is_recovery_available
 * @param _is_recovery_available New value for member is_recovery_available
 */
void FallDownState_::is_recovery_available(
        bool _is_recovery_available)
{
    m_is_recovery_available = _is_recovery_available;
}

/*!
 * @brief This function returns the value of member is_recovery_available
 * @return Value of member is_recovery_available
 */
bool FallDownState_::is_recovery_available() const
{
    return m_is_recovery_available;
}

/*!
 * @brief This function returns a reference to member is_recovery_available
 * @return Reference to member is_recovery_available
 */
bool& FallDownState_::is_recovery_available()
{
    return m_is_recovery_available;
}





} // namespace dds_


} // namespace msg


} // namespace booster_interface

