// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file FallDownState.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef _FAST_DDS_GENERATED_BOOSTER_INTERFACE_MSG_DDS__FALLDOWNSTATE_H_
#define _FAST_DDS_GENERATED_BOOSTER_INTERFACE_MSG_DDS__FALLDOWNSTATE_H_


#include <fastrtps/utils/fixed_size_string.hpp>

#include <stdint.h>
#include <array>
#include <string>
#include <vector>
#include <map>
#include <bitset>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(FALLDOWNSTATE_SOURCE)
#define FALLDOWNSTATE_DllAPI __declspec( dllexport )
#else
#define FALLDOWNSTATE_DllAPI __declspec( dllimport )
#endif // FALLDOWNSTATE_SOURCE
#else
#define FALLDOWNSTATE_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define FALLDOWNSTATE_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
} // namespace fastcdr
} // namespace eprosima



namespace booster_interface {
    namespace msg {
        namespace dds_ {
            /*!
             * @brief This class represents the enumeration FallDownStateType_ defined by the user in the IDL file.
             * @ingroup FallDownState
             */
            enum FallDownStateType_ : uint32_t
            {
                IS_READY,
                IS_FALLING,
                HAS_FALLEN,
                IS_GETTING_UP
            };


            /*!
             * @brief This class represents the structure FallDownState_ defined by the user in the IDL file.
             * @ingroup FallDownState
             */
            class FallDownState_
            {
            public:

                /*!
                 * @brief Default constructor.
                 */
                eProsima_user_DllExport FallDownState_();

                /*!
                 * @brief Default destructor.
                 */
                eProsima_user_DllExport ~FallDownState_();

                /*!
                 * @brief Copy constructor.
                 * @param x Reference to the object booster_interface::msg::dds_::FallDownState_ that will be copied.
                 */
                eProsima_user_DllExport FallDownState_(
                        const FallDownState_& x);

                /*!
                 * @brief Move constructor.
                 * @param x Reference to the object booster_interface::msg::dds_::FallDownState_ that will be copied.
                 */
                eProsima_user_DllExport FallDownState_(
                        FallDownState_&& x) noexcept;

                /*!
                 * @brief Copy assignment.
                 * @param x Reference to the object booster_interface::msg::dds_::FallDownState_ that will be copied.
                 */
                eProsima_user_DllExport FallDownState_& operator =(
                        const FallDownState_& x);

                /*!
                 * @brief Move assignment.
                 * @param x Reference to the object booster_interface::msg::dds_::FallDownState_ that will be copied.
                 */
                eProsima_user_DllExport FallDownState_& operator =(
                        FallDownState_&& x) noexcept;

                /*!
                 * @brief Comparison operator.
                 * @param x booster_interface::msg::dds_::FallDownState_ object to compare.
                 */
                eProsima_user_DllExport bool operator ==(
                        const FallDownState_& x) const;

                /*!
                 * @brief Comparison operator.
                 * @param x booster_interface::msg::dds_::FallDownState_ object to compare.
                 */
                eProsima_user_DllExport bool operator !=(
                        const FallDownState_& x) const;

                /*!
                 * @brief This function sets a value in member fall_down_state
                 * @param _fall_down_state New value for member fall_down_state
                 */
                eProsima_user_DllExport void fall_down_state(
                        booster_interface::msg::dds_::FallDownStateType_ _fall_down_state);

                /*!
                 * @brief This function returns the value of member fall_down_state
                 * @return Value of member fall_down_state
                 */
                eProsima_user_DllExport booster_interface::msg::dds_::FallDownStateType_ fall_down_state() const;

                /*!
                 * @brief This function returns a reference to member fall_down_state
                 * @return Reference to member fall_down_state
                 */
                eProsima_user_DllExport booster_interface::msg::dds_::FallDownStateType_& fall_down_state();


                /*!
                 * @brief This function sets a value in member is_recovery_available
                 * @param _is_recovery_available New value for member is_recovery_available
                 */
                eProsima_user_DllExport void is_recovery_available(
                        bool _is_recovery_available);

                /*!
                 * @brief This function returns the value of member is_recovery_available
                 * @return Value of member is_recovery_available
                 */
                eProsima_user_DllExport bool is_recovery_available() const;

                /*!
                 * @brief This function returns a reference to member is_recovery_available
                 * @return Reference to member is_recovery_available
                 */
                eProsima_user_DllExport bool& is_recovery_available();


                /*!
                * @brief This function returns the maximum serialized size of an object
                * depending on the buffer alignment.
                * @param current_alignment Buffer alignment.
                * @return Maximum serialized size.
                */
                eProsima_user_DllExport static size_t getMaxCdrSerializedSize(
                        size_t current_alignment = 0);

                /*!
                 * @brief This function returns the serialized size of a data depending on the buffer alignment.
                 * @param data Data which is calculated its serialized size.
                 * @param current_alignment Buffer alignment.
                 * @return Serialized size.
                 */
                eProsima_user_DllExport static size_t getCdrSerializedSize(
                        const booster_interface::msg::dds_::FallDownState_& data,
                        size_t current_alignment = 0);



                /*!
                 * @brief This function serializes an object using CDR serialization.
                 * @param cdr CDR serialization object.
                 */
                eProsima_user_DllExport void serialize(
                        eprosima::fastcdr::Cdr& cdr) const;

                /*!
                 * @brief This function deserializes an object using CDR serialization.
                 * @param cdr CDR serialization object.
                 */
                eProsima_user_DllExport void deserialize(
                        eprosima::fastcdr::Cdr& cdr);




                /*!
                * @brief This function tells you if the Key has been defined for this type
                */
                eProsima_user_DllExport static bool isKeyDefined();

                /*!
                * @brief This function serializes the key members of an object using CDR serialization.
                * @param cdr CDR serialization object.
                */
                eProsima_user_DllExport void serializeKey(
                        eprosima::fastcdr::Cdr& cdr) const;


            private:

                booster_interface::msg::dds_::FallDownStateType_ m_fall_down_state;
                bool m_is_recovery_available;

            };

        } // namespace dds_
    } // namespace msg
} // namespace booster_interface

#endif // _FAST_DDS_GENERATED_BOOSTER_INTERFACE_MSG_DDS__FALLDOWNSTATE_H_



