// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file ImuState.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef _FAST_DDS_GENERATED_BOOSTER_INTERFACE_MSG_DDS__IMUSTATE_H_
#define _FAST_DDS_GENERATED_BOOSTER_INTERFACE_MSG_DDS__IMUSTATE_H_


#include <fastrtps/utils/fixed_size_string.hpp>

#include <stdint.h>
#include <array>
#include <string>
#include <vector>
#include <map>
#include <bitset>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(IMUSTATE_SOURCE)
#define IMUSTATE_DllAPI __declspec( dllexport )
#else
#define IMUSTATE_DllAPI __declspec( dllimport )
#endif // IMUSTATE_SOURCE
#else
#define IMUSTATE_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define IMUSTATE_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
} // namespace fastcdr
} // namespace eprosima



namespace booster_interface {
    namespace msg {
        namespace dds_ {


            /*!
             * @brief This class represents the structure ImuState_ defined by the user in the IDL file.
             * @ingroup ImuState
             */
            class ImuState_
            {
            public:

                /*!
                 * @brief Default constructor.
                 */
                eProsima_user_DllExport ImuState_();

                /*!
                 * @brief Default destructor.
                 */
                eProsima_user_DllExport ~ImuState_();

                /*!
                 * @brief Copy constructor.
                 * @param x Reference to the object booster_interface::msg::dds_::ImuState_ that will be copied.
                 */
                eProsima_user_DllExport ImuState_(
                        const ImuState_& x);

                /*!
                 * @brief Move constructor.
                 * @param x Reference to the object booster_interface::msg::dds_::ImuState_ that will be copied.
                 */
                eProsima_user_DllExport ImuState_(
                        ImuState_&& x) noexcept;

                /*!
                 * @brief Copy assignment.
                 * @param x Reference to the object booster_interface::msg::dds_::ImuState_ that will be copied.
                 */
                eProsima_user_DllExport ImuState_& operator =(
                        const ImuState_& x);

                /*!
                 * @brief Move assignment.
                 * @param x Reference to the object booster_interface::msg::dds_::ImuState_ that will be copied.
                 */
                eProsima_user_DllExport ImuState_& operator =(
                        ImuState_&& x) noexcept;

                /*!
                 * @brief Comparison operator.
                 * @param x booster_interface::msg::dds_::ImuState_ object to compare.
                 */
                eProsima_user_DllExport bool operator ==(
                        const ImuState_& x) const;

                /*!
                 * @brief Comparison operator.
                 * @param x booster_interface::msg::dds_::ImuState_ object to compare.
                 */
                eProsima_user_DllExport bool operator !=(
                        const ImuState_& x) const;

                /*!
                 * @brief This function copies the value in member rpy
                 * @param _rpy New value to be copied in member rpy
                 */
                eProsima_user_DllExport void rpy(
                        const std::array<float, 3>& _rpy);

                /*!
                 * @brief This function moves the value in member rpy
                 * @param _rpy New value to be moved in member rpy
                 */
                eProsima_user_DllExport void rpy(
                        std::array<float, 3>&& _rpy);

                /*!
                 * @brief This function returns a constant reference to member rpy
                 * @return Constant reference to member rpy
                 */
                eProsima_user_DllExport const std::array<float, 3>& rpy() const;

                /*!
                 * @brief This function returns a reference to member rpy
                 * @return Reference to member rpy
                 */
                eProsima_user_DllExport std::array<float, 3>& rpy();


                /*!
                 * @brief This function copies the value in member gyro
                 * @param _gyro New value to be copied in member gyro
                 */
                eProsima_user_DllExport void gyro(
                        const std::array<float, 3>& _gyro);

                /*!
                 * @brief This function moves the value in member gyro
                 * @param _gyro New value to be moved in member gyro
                 */
                eProsima_user_DllExport void gyro(
                        std::array<float, 3>&& _gyro);

                /*!
                 * @brief This function returns a constant reference to member gyro
                 * @return Constant reference to member gyro
                 */
                eProsima_user_DllExport const std::array<float, 3>& gyro() const;

                /*!
                 * @brief This function returns a reference to member gyro
                 * @return Reference to member gyro
                 */
                eProsima_user_DllExport std::array<float, 3>& gyro();


                /*!
                 * @brief This function copies the value in member acc
                 * @param _acc New value to be copied in member acc
                 */
                eProsima_user_DllExport void acc(
                        const std::array<float, 3>& _acc);

                /*!
                 * @brief This function moves the value in member acc
                 * @param _acc New value to be moved in member acc
                 */
                eProsima_user_DllExport void acc(
                        std::array<float, 3>&& _acc);

                /*!
                 * @brief This function returns a constant reference to member acc
                 * @return Constant reference to member acc
                 */
                eProsima_user_DllExport const std::array<float, 3>& acc() const;

                /*!
                 * @brief This function returns a reference to member acc
                 * @return Reference to member acc
                 */
                eProsima_user_DllExport std::array<float, 3>& acc();


                /*!
                * @brief This function returns the maximum serialized size of an object
                * depending on the buffer alignment.
                * @param current_alignment Buffer alignment.
                * @return Maximum serialized size.
                */
                eProsima_user_DllExport static size_t getMaxCdrSerializedSize(
                        size_t current_alignment = 0);

                /*!
                 * @brief This function returns the serialized size of a data depending on the buffer alignment.
                 * @param data Data which is calculated its serialized size.
                 * @param current_alignment Buffer alignment.
                 * @return Serialized size.
                 */
                eProsima_user_DllExport static size_t getCdrSerializedSize(
                        const booster_interface::msg::dds_::ImuState_& data,
                        size_t current_alignment = 0);



                /*!
                 * @brief This function serializes an object using CDR serialization.
                 * @param cdr CDR serialization object.
                 */
                eProsima_user_DllExport void serialize(
                        eprosima::fastcdr::Cdr& cdr) const;

                /*!
                 * @brief This function deserializes an object using CDR serialization.
                 * @param cdr CDR serialization object.
                 */
                eProsima_user_DllExport void deserialize(
                        eprosima::fastcdr::Cdr& cdr);




                /*!
                * @brief This function tells you if the Key has been defined for this type
                */
                eProsima_user_DllExport static bool isKeyDefined();

                /*!
                * @brief This function serializes the key members of an object using CDR serialization.
                * @param cdr CDR serialization object.
                */
                eProsima_user_DllExport void serializeKey(
                        eprosima::fastcdr::Cdr& cdr) const;


            private:

                std::array<float, 3> m_rpy;
                std::array<float, 3> m_gyro;
                std::array<float, 3> m_acc;

            };

        } // namespace dds_
    } // namespace msg
} // namespace booster_interface

#endif // _FAST_DDS_GENERATED_BOOSTER_INTERFACE_MSG_DDS__IMUSTATE_H_



