// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file ImuState.cpp
 * This source file contains the implementation of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "ImuState.h"

#include <fastcdr/Cdr.h>


#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

namespace helper { namespace internal {

enum class Size {
    UInt8,
    UInt16,
    UInt32,
    UInt64,
};

constexpr Size get_size(int s) {
    return (s <= 8 ) ? Size::UInt8:
           (s <= 16) ? Size::UInt16:
           (s <= 32) ? Size::UInt32: Size::UInt64;
}

template<Size s>
struct FindTypeH;

template<>
struct FindTypeH<Size::UInt8> {
    using type = std::uint8_t;
};

template<>
struct FindTypeH<Size::UInt16> {
    using type = std::uint16_t;
};

template<>
struct FindTypeH<Size::UInt32> {
    using type = std::uint32_t;
};

template<>
struct FindTypeH<Size::UInt64> {
    using type = std::uint64_t;
};
}

template<int S>
struct FindType {
    using type = typename internal::FindTypeH<internal::get_size(S)>::type;
};
}

#define booster_interface_msg_dds__ImuState__max_cdr_typesize 36ULL;


namespace booster_interface {

namespace msg {

namespace dds_ {



ImuState_::ImuState_()
{
    // float m_rpy
    memset(&m_rpy, 0, ((3)) * 4);
    // float m_gyro
    memset(&m_gyro, 0, ((3)) * 4);
    // float m_acc
    memset(&m_acc, 0, ((3)) * 4);

}

ImuState_::~ImuState_()
{
}

ImuState_::ImuState_(
        const ImuState_& x)
{
    m_rpy = x.m_rpy;


    m_gyro = x.m_gyro;


    m_acc = x.m_acc;

}

ImuState_::ImuState_(
        ImuState_&& x) noexcept
{
    m_rpy = std::move(x.m_rpy);


    m_gyro = std::move(x.m_gyro);


    m_acc = std::move(x.m_acc);

}

ImuState_& ImuState_::operator =(
        const ImuState_& x)
{
    m_rpy = x.m_rpy;


    m_gyro = x.m_gyro;


    m_acc = x.m_acc;

    return *this;
}

ImuState_& ImuState_::operator =(
        ImuState_&& x) noexcept
{
    m_rpy = std::move(x.m_rpy);


    m_gyro = std::move(x.m_gyro);


    m_acc = std::move(x.m_acc);

    return *this;
}

bool ImuState_::operator ==(
        const ImuState_& x) const
{
    return (m_rpy == x.m_rpy &&
           m_gyro == x.m_gyro &&
           m_acc == x.m_acc);
}

bool ImuState_::operator !=(
        const ImuState_& x) const
{
    return !(*this == x);
}

size_t ImuState_::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    static_cast<void>(current_alignment);
    return booster_interface_msg_dds__ImuState__max_cdr_typesize;
}

size_t ImuState_::getCdrSerializedSize(
        const ImuState_& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;

    current_alignment += (((3)) * 4) + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);



    current_alignment += (((3)) * 4) + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);



    current_alignment += (((3)) * 4) + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);



    return current_alignment - initial_alignment;
}


void ImuState_::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{
    scdr << m_rpy;


    scdr << m_gyro;


    scdr << m_acc;


}

void ImuState_::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{
    dcdr >> m_rpy;



    dcdr >> m_gyro;



    dcdr >> m_acc;


}


bool ImuState_::isKeyDefined()
{
    return false;
}

void ImuState_::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
}

/*!
 * @brief This function copies the value in member rpy
 * @param _rpy New value to be copied in member rpy
 */
void ImuState_::rpy(
        const std::array<float, 3>& _rpy)
{
    m_rpy = _rpy;
}

/*!
 * @brief This function moves the value in member rpy
 * @param _rpy New value to be moved in member rpy
 */
void ImuState_::rpy(
        std::array<float, 3>&& _rpy)
{
    m_rpy = std::move(_rpy);
}

/*!
 * @brief This function returns a constant reference to member rpy
 * @return Constant reference to member rpy
 */
const std::array<float, 3>& ImuState_::rpy() const
{
    return m_rpy;
}

/*!
 * @brief This function returns a reference to member rpy
 * @return Reference to member rpy
 */
std::array<float, 3>& ImuState_::rpy()
{
    return m_rpy;
}


/*!
 * @brief This function copies the value in member gyro
 * @param _gyro New value to be copied in member gyro
 */
void ImuState_::gyro(
        const std::array<float, 3>& _gyro)
{
    m_gyro = _gyro;
}

/*!
 * @brief This function moves the value in member gyro
 * @param _gyro New value to be moved in member gyro
 */
void ImuState_::gyro(
        std::array<float, 3>&& _gyro)
{
    m_gyro = std::move(_gyro);
}

/*!
 * @brief This function returns a constant reference to member gyro
 * @return Constant reference to member gyro
 */
const std::array<float, 3>& ImuState_::gyro() const
{
    return m_gyro;
}

/*!
 * @brief This function returns a reference to member gyro
 * @return Reference to member gyro
 */
std::array<float, 3>& ImuState_::gyro()
{
    return m_gyro;
}


/*!
 * @brief This function copies the value in member acc
 * @param _acc New value to be copied in member acc
 */
void ImuState_::acc(
        const std::array<float, 3>& _acc)
{
    m_acc = _acc;
}

/*!
 * @brief This function moves the value in member acc
 * @param _acc New value to be moved in member acc
 */
void ImuState_::acc(
        std::array<float, 3>&& _acc)
{
    m_acc = std::move(_acc);
}

/*!
 * @brief This function returns a constant reference to member acc
 * @return Constant reference to member acc
 */
const std::array<float, 3>& ImuState_::acc() const
{
    return m_acc;
}

/*!
 * @brief This function returns a reference to member acc
 * @return Reference to member acc
 */
std::array<float, 3>& ImuState_::acc()
{
    return m_acc;
}





} // namespace dds_


} // namespace msg


} // namespace booster_interface

