// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file LowCmd.cpp
 * This source file contains the implementation of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "LowCmd.h"

#include <fastcdr/Cdr.h>


#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

namespace helper { namespace internal {

enum class Size {
    UInt8,
    UInt16,
    UInt32,
    UInt64,
};

constexpr Size get_size(int s) {
    return (s <= 8 ) ? Size::UInt8:
           (s <= 16) ? Size::UInt16:
           (s <= 32) ? Size::UInt32: Size::UInt64;
}

template<Size s>
struct FindTypeH;

template<>
struct FindTypeH<Size::UInt8> {
    using type = std::uint8_t;
};

template<>
struct FindTypeH<Size::UInt16> {
    using type = std::uint16_t;
};

template<>
struct FindTypeH<Size::UInt32> {
    using type = std::uint32_t;
};

template<>
struct FindTypeH<Size::UInt64> {
    using type = std::uint64_t;
};
}

template<int S>
struct FindType {
    using type = typename internal::FindTypeH<internal::get_size(S)>::type;
};
}

#define booster_interface_msg_dds__MotorCmd__max_cdr_typesize 28ULL;

#define booster_interface_msg_dds__LowCmd__max_cdr_typesize 2812ULL;


namespace booster_interface {

namespace msg {

namespace dds_ {





LowCmd_::LowCmd_()
{
    // booster_interface::msg::dds_::CmdType_ m_cmd_type
    m_cmd_type = booster_interface::msg::dds_::PARALLEL;
    // sequence<booster_interface::msg::dds_::MotorCmd_> m_motor_cmd


}

LowCmd_::~LowCmd_()
{
}

LowCmd_::LowCmd_(
        const LowCmd_& x)
{
    m_cmd_type = x.m_cmd_type;


    m_motor_cmd = x.m_motor_cmd;

}

LowCmd_::LowCmd_(
        LowCmd_&& x) noexcept
{
    m_cmd_type = x.m_cmd_type;


    m_motor_cmd = std::move(x.m_motor_cmd);

}

LowCmd_& LowCmd_::operator =(
        const LowCmd_& x)
{
    m_cmd_type = x.m_cmd_type;


    m_motor_cmd = x.m_motor_cmd;

    return *this;
}

LowCmd_& LowCmd_::operator =(
        LowCmd_&& x) noexcept
{
    m_cmd_type = x.m_cmd_type;


    m_motor_cmd = std::move(x.m_motor_cmd);

    return *this;
}

bool LowCmd_::operator ==(
        const LowCmd_& x) const
{
    return (m_cmd_type == x.m_cmd_type &&
           m_motor_cmd == x.m_motor_cmd);
}

bool LowCmd_::operator !=(
        const LowCmd_& x) const
{
    return !(*this == x);
}

size_t LowCmd_::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    static_cast<void>(current_alignment);
    return booster_interface_msg_dds__LowCmd__max_cdr_typesize;
}

size_t LowCmd_::getCdrSerializedSize(
        const LowCmd_& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;

    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    for(size_t a = 0; a < data.motor_cmd().size(); ++a)
    {
        current_alignment += booster_interface::msg::dds_::MotorCmd_::getCdrSerializedSize(data.motor_cmd().at(a), current_alignment);
    }



    return current_alignment - initial_alignment;
}


void LowCmd_::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{
    scdr << (uint32_t)m_cmd_type;

    scdr << m_motor_cmd;


}

void LowCmd_::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{
    {
        uint32_t enum_value = 0;
        dcdr >> enum_value;
        m_cmd_type = (booster_interface::msg::dds_::CmdType_)enum_value;
    }



    dcdr >> m_motor_cmd;


}


bool LowCmd_::isKeyDefined()
{
    return false;
}

void LowCmd_::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
}

/*!
 * @brief This function sets a value in member cmd_type
 * @param _cmd_type New value for member cmd_type
 */
void LowCmd_::cmd_type(
        booster_interface::msg::dds_::CmdType_ _cmd_type)
{
    m_cmd_type = _cmd_type;
}

/*!
 * @brief This function returns the value of member cmd_type
 * @return Value of member cmd_type
 */
booster_interface::msg::dds_::CmdType_ LowCmd_::cmd_type() const
{
    return m_cmd_type;
}

/*!
 * @brief This function returns a reference to member cmd_type
 * @return Reference to member cmd_type
 */
booster_interface::msg::dds_::CmdType_& LowCmd_::cmd_type()
{
    return m_cmd_type;
}


/*!
 * @brief This function copies the value in member motor_cmd
 * @param _motor_cmd New value to be copied in member motor_cmd
 */
void LowCmd_::motor_cmd(
        const std::vector<booster_interface::msg::dds_::MotorCmd_>& _motor_cmd)
{
    m_motor_cmd = _motor_cmd;
}

/*!
 * @brief This function moves the value in member motor_cmd
 * @param _motor_cmd New value to be moved in member motor_cmd
 */
void LowCmd_::motor_cmd(
        std::vector<booster_interface::msg::dds_::MotorCmd_>&& _motor_cmd)
{
    m_motor_cmd = std::move(_motor_cmd);
}

/*!
 * @brief This function returns a constant reference to member motor_cmd
 * @return Constant reference to member motor_cmd
 */
const std::vector<booster_interface::msg::dds_::MotorCmd_>& LowCmd_::motor_cmd() const
{
    return m_motor_cmd;
}

/*!
 * @brief This function returns a reference to member motor_cmd
 * @return Reference to member motor_cmd
 */
std::vector<booster_interface::msg::dds_::MotorCmd_>& LowCmd_::motor_cmd()
{
    return m_motor_cmd;
}





} // namespace dds_


} // namespace msg


} // namespace booster_interface

