// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file LowCmd.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef _FAST_DDS_GENERATED_BOOSTER_INTERFACE_MSG_DDS__LOWCMD_H_
#define _FAST_DDS_GENERATED_BOOSTER_INTERFACE_MSG_DDS__LOWCMD_H_

#include "MotorCmd.h"

#include <fastrtps/utils/fixed_size_string.hpp>

#include <stdint.h>
#include <array>
#include <string>
#include <vector>
#include <map>
#include <bitset>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(LOWCMD_SOURCE)
#define LOWCMD_DllAPI __declspec( dllexport )
#else
#define LOWCMD_DllAPI __declspec( dllimport )
#endif // LOWCMD_SOURCE
#else
#define LOWCMD_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define LOWCMD_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
} // namespace fastcdr
} // namespace eprosima



namespace booster_interface {
    namespace msg {
        namespace dds_ {
            /*!
             * @brief This class represents the enumeration CmdType_ defined by the user in the IDL file.
             * @ingroup LowCmd
             */
            enum CmdType_ : uint32_t
            {
                PARALLEL,
                SERIAL
            };




            /*!
             * @brief This class represents the structure LowCmd_ defined by the user in the IDL file.
             * @ingroup LowCmd
             */
            class LowCmd_
            {
            public:

                /*!
                 * @brief Default constructor.
                 */
                eProsima_user_DllExport LowCmd_();

                /*!
                 * @brief Default destructor.
                 */
                eProsima_user_DllExport ~LowCmd_();

                /*!
                 * @brief Copy constructor.
                 * @param x Reference to the object booster_interface::msg::dds_::LowCmd_ that will be copied.
                 */
                eProsima_user_DllExport LowCmd_(
                        const LowCmd_& x);

                /*!
                 * @brief Move constructor.
                 * @param x Reference to the object booster_interface::msg::dds_::LowCmd_ that will be copied.
                 */
                eProsima_user_DllExport LowCmd_(
                        LowCmd_&& x) noexcept;

                /*!
                 * @brief Copy assignment.
                 * @param x Reference to the object booster_interface::msg::dds_::LowCmd_ that will be copied.
                 */
                eProsima_user_DllExport LowCmd_& operator =(
                        const LowCmd_& x);

                /*!
                 * @brief Move assignment.
                 * @param x Reference to the object booster_interface::msg::dds_::LowCmd_ that will be copied.
                 */
                eProsima_user_DllExport LowCmd_& operator =(
                        LowCmd_&& x) noexcept;

                /*!
                 * @brief Comparison operator.
                 * @param x booster_interface::msg::dds_::LowCmd_ object to compare.
                 */
                eProsima_user_DllExport bool operator ==(
                        const LowCmd_& x) const;

                /*!
                 * @brief Comparison operator.
                 * @param x booster_interface::msg::dds_::LowCmd_ object to compare.
                 */
                eProsima_user_DllExport bool operator !=(
                        const LowCmd_& x) const;

                /*!
                 * @brief This function sets a value in member cmd_type
                 * @param _cmd_type New value for member cmd_type
                 */
                eProsima_user_DllExport void cmd_type(
                        booster_interface::msg::dds_::CmdType_ _cmd_type);

                /*!
                 * @brief This function returns the value of member cmd_type
                 * @return Value of member cmd_type
                 */
                eProsima_user_DllExport booster_interface::msg::dds_::CmdType_ cmd_type() const;

                /*!
                 * @brief This function returns a reference to member cmd_type
                 * @return Reference to member cmd_type
                 */
                eProsima_user_DllExport booster_interface::msg::dds_::CmdType_& cmd_type();


                /*!
                 * @brief This function copies the value in member motor_cmd
                 * @param _motor_cmd New value to be copied in member motor_cmd
                 */
                eProsima_user_DllExport void motor_cmd(
                        const std::vector<booster_interface::msg::dds_::MotorCmd_>& _motor_cmd);

                /*!
                 * @brief This function moves the value in member motor_cmd
                 * @param _motor_cmd New value to be moved in member motor_cmd
                 */
                eProsima_user_DllExport void motor_cmd(
                        std::vector<booster_interface::msg::dds_::MotorCmd_>&& _motor_cmd);

                /*!
                 * @brief This function returns a constant reference to member motor_cmd
                 * @return Constant reference to member motor_cmd
                 */
                eProsima_user_DllExport const std::vector<booster_interface::msg::dds_::MotorCmd_>& motor_cmd() const;

                /*!
                 * @brief This function returns a reference to member motor_cmd
                 * @return Reference to member motor_cmd
                 */
                eProsima_user_DllExport std::vector<booster_interface::msg::dds_::MotorCmd_>& motor_cmd();


                /*!
                * @brief This function returns the maximum serialized size of an object
                * depending on the buffer alignment.
                * @param current_alignment Buffer alignment.
                * @return Maximum serialized size.
                */
                eProsima_user_DllExport static size_t getMaxCdrSerializedSize(
                        size_t current_alignment = 0);

                /*!
                 * @brief This function returns the serialized size of a data depending on the buffer alignment.
                 * @param data Data which is calculated its serialized size.
                 * @param current_alignment Buffer alignment.
                 * @return Serialized size.
                 */
                eProsima_user_DllExport static size_t getCdrSerializedSize(
                        const booster_interface::msg::dds_::LowCmd_& data,
                        size_t current_alignment = 0);



                /*!
                 * @brief This function serializes an object using CDR serialization.
                 * @param cdr CDR serialization object.
                 */
                eProsima_user_DllExport void serialize(
                        eprosima::fastcdr::Cdr& cdr) const;

                /*!
                 * @brief This function deserializes an object using CDR serialization.
                 * @param cdr CDR serialization object.
                 */
                eProsima_user_DllExport void deserialize(
                        eprosima::fastcdr::Cdr& cdr);




                /*!
                * @brief This function tells you if the Key has been defined for this type
                */
                eProsima_user_DllExport static bool isKeyDefined();

                /*!
                * @brief This function serializes the key members of an object using CDR serialization.
                * @param cdr CDR serialization object.
                */
                eProsima_user_DllExport void serializeKey(
                        eprosima::fastcdr::Cdr& cdr) const;


            private:

                booster_interface::msg::dds_::CmdType_ m_cmd_type;
                std::vector<booster_interface::msg::dds_::MotorCmd_> m_motor_cmd;

            };

        } // namespace dds_
    } // namespace msg
} // namespace booster_interface

#endif // _FAST_DDS_GENERATED_BOOSTER_INTERFACE_MSG_DDS__LOWCMD_H_



