// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file LowState.cpp
 * This source file contains the implementation of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "LowState.h"

#include <fastcdr/Cdr.h>


#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

namespace helper { namespace internal {

enum class Size {
    UInt8,
    UInt16,
    UInt32,
    UInt64,
};

constexpr Size get_size(int s) {
    return (s <= 8 ) ? Size::UInt8:
           (s <= 16) ? Size::UInt16:
           (s <= 32) ? Size::UInt32: Size::UInt64;
}

template<Size s>
struct FindTypeH;

template<>
struct FindTypeH<Size::UInt8> {
    using type = std::uint8_t;
};

template<>
struct FindTypeH<Size::UInt16> {
    using type = std::uint16_t;
};

template<>
struct FindTypeH<Size::UInt32> {
    using type = std::uint32_t;
};

template<>
struct FindTypeH<Size::UInt64> {
    using type = std::uint64_t;
};
}

template<int S>
struct FindType {
    using type = typename internal::FindTypeH<internal::get_size(S)>::type;
};
}

#define booster_interface_msg_dds__MotorState__max_cdr_typesize 36ULL;
#define booster_interface_msg_dds__ImuState__max_cdr_typesize 36ULL;
#define booster_interface_msg_dds__LowState__max_cdr_typesize 7252ULL;


namespace booster_interface {

namespace msg {

namespace dds_ {





LowState_::LowState_()
{
    // booster_interface::msg::dds_::ImuState_ m_imu_state

    // sequence<booster_interface::msg::dds_::MotorState_> m_motor_state_parallel

    // sequence<booster_interface::msg::dds_::MotorState_> m_motor_state_serial


}

LowState_::~LowState_()
{
}

LowState_::LowState_(
        const LowState_& x)
{
    m_imu_state = x.m_imu_state;


    m_motor_state_parallel = x.m_motor_state_parallel;


    m_motor_state_serial = x.m_motor_state_serial;

}

LowState_::LowState_(
        LowState_&& x) noexcept
{
    m_imu_state = std::move(x.m_imu_state);


    m_motor_state_parallel = std::move(x.m_motor_state_parallel);


    m_motor_state_serial = std::move(x.m_motor_state_serial);

}

LowState_& LowState_::operator =(
        const LowState_& x)
{
    m_imu_state = x.m_imu_state;


    m_motor_state_parallel = x.m_motor_state_parallel;


    m_motor_state_serial = x.m_motor_state_serial;

    return *this;
}

LowState_& LowState_::operator =(
        LowState_&& x) noexcept
{
    m_imu_state = std::move(x.m_imu_state);


    m_motor_state_parallel = std::move(x.m_motor_state_parallel);


    m_motor_state_serial = std::move(x.m_motor_state_serial);

    return *this;
}

bool LowState_::operator ==(
        const LowState_& x) const
{
    return (m_imu_state == x.m_imu_state &&
           m_motor_state_parallel == x.m_motor_state_parallel &&
           m_motor_state_serial == x.m_motor_state_serial);
}

bool LowState_::operator !=(
        const LowState_& x) const
{
    return !(*this == x);
}

size_t LowState_::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    static_cast<void>(current_alignment);
    return booster_interface_msg_dds__LowState__max_cdr_typesize;
}

size_t LowState_::getCdrSerializedSize(
        const LowState_& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;

    current_alignment += booster_interface::msg::dds_::ImuState_::getCdrSerializedSize(data.imu_state(), current_alignment);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    for(size_t a = 0; a < data.motor_state_parallel().size(); ++a)
    {
        current_alignment += booster_interface::msg::dds_::MotorState_::getCdrSerializedSize(data.motor_state_parallel().at(a), current_alignment);
    }



    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    for(size_t a = 0; a < data.motor_state_serial().size(); ++a)
    {
        current_alignment += booster_interface::msg::dds_::MotorState_::getCdrSerializedSize(data.motor_state_serial().at(a), current_alignment);
    }



    return current_alignment - initial_alignment;
}


void LowState_::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{
    scdr << m_imu_state;

    scdr << m_motor_state_parallel;


    scdr << m_motor_state_serial;


}

void LowState_::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{
    dcdr >> m_imu_state;



    dcdr >> m_motor_state_parallel;



    dcdr >> m_motor_state_serial;


}


bool LowState_::isKeyDefined()
{
    return false;
}

void LowState_::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
}

/*!
 * @brief This function copies the value in member imu_state
 * @param _imu_state New value to be copied in member imu_state
 */
void LowState_::imu_state(
        const booster_interface::msg::dds_::ImuState_& _imu_state)
{
    m_imu_state = _imu_state;
}

/*!
 * @brief This function moves the value in member imu_state
 * @param _imu_state New value to be moved in member imu_state
 */
void LowState_::imu_state(
        booster_interface::msg::dds_::ImuState_&& _imu_state)
{
    m_imu_state = std::move(_imu_state);
}

/*!
 * @brief This function returns a constant reference to member imu_state
 * @return Constant reference to member imu_state
 */
const booster_interface::msg::dds_::ImuState_& LowState_::imu_state() const
{
    return m_imu_state;
}

/*!
 * @brief This function returns a reference to member imu_state
 * @return Reference to member imu_state
 */
booster_interface::msg::dds_::ImuState_& LowState_::imu_state()
{
    return m_imu_state;
}


/*!
 * @brief This function copies the value in member motor_state_parallel
 * @param _motor_state_parallel New value to be copied in member motor_state_parallel
 */
void LowState_::motor_state_parallel(
        const std::vector<booster_interface::msg::dds_::MotorState_>& _motor_state_parallel)
{
    m_motor_state_parallel = _motor_state_parallel;
}

/*!
 * @brief This function moves the value in member motor_state_parallel
 * @param _motor_state_parallel New value to be moved in member motor_state_parallel
 */
void LowState_::motor_state_parallel(
        std::vector<booster_interface::msg::dds_::MotorState_>&& _motor_state_parallel)
{
    m_motor_state_parallel = std::move(_motor_state_parallel);
}

/*!
 * @brief This function returns a constant reference to member motor_state_parallel
 * @return Constant reference to member motor_state_parallel
 */
const std::vector<booster_interface::msg::dds_::MotorState_>& LowState_::motor_state_parallel() const
{
    return m_motor_state_parallel;
}

/*!
 * @brief This function returns a reference to member motor_state_parallel
 * @return Reference to member motor_state_parallel
 */
std::vector<booster_interface::msg::dds_::MotorState_>& LowState_::motor_state_parallel()
{
    return m_motor_state_parallel;
}


/*!
 * @brief This function copies the value in member motor_state_serial
 * @param _motor_state_serial New value to be copied in member motor_state_serial
 */
void LowState_::motor_state_serial(
        const std::vector<booster_interface::msg::dds_::MotorState_>& _motor_state_serial)
{
    m_motor_state_serial = _motor_state_serial;
}

/*!
 * @brief This function moves the value in member motor_state_serial
 * @param _motor_state_serial New value to be moved in member motor_state_serial
 */
void LowState_::motor_state_serial(
        std::vector<booster_interface::msg::dds_::MotorState_>&& _motor_state_serial)
{
    m_motor_state_serial = std::move(_motor_state_serial);
}

/*!
 * @brief This function returns a constant reference to member motor_state_serial
 * @return Constant reference to member motor_state_serial
 */
const std::vector<booster_interface::msg::dds_::MotorState_>& LowState_::motor_state_serial() const
{
    return m_motor_state_serial;
}

/*!
 * @brief This function returns a reference to member motor_state_serial
 * @return Reference to member motor_state_serial
 */
std::vector<booster_interface::msg::dds_::MotorState_>& LowState_::motor_state_serial()
{
    return m_motor_state_serial;
}





} // namespace dds_


} // namespace msg


} // namespace booster_interface

