// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file LowState.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef _FAST_DDS_GENERATED_BOOSTER_INTERFACE_MSG_DDS__LOWSTATE_H_
#define _FAST_DDS_GENERATED_BOOSTER_INTERFACE_MSG_DDS__LOWSTATE_H_

#include "MotorState.h"
#include "ImuState.h"

#include <fastrtps/utils/fixed_size_string.hpp>

#include <stdint.h>
#include <array>
#include <string>
#include <vector>
#include <map>
#include <bitset>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(LOWSTATE_SOURCE)
#define LOWSTATE_DllAPI __declspec( dllexport )
#else
#define LOWSTATE_DllAPI __declspec( dllimport )
#endif // LOWSTATE_SOURCE
#else
#define LOWSTATE_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define LOWSTATE_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
} // namespace fastcdr
} // namespace eprosima



namespace booster_interface {
    namespace msg {
        namespace dds_ {




            /*!
             * @brief This class represents the structure LowState_ defined by the user in the IDL file.
             * @ingroup LowState
             */
            class LowState_
            {
            public:

                /*!
                 * @brief Default constructor.
                 */
                eProsima_user_DllExport LowState_();

                /*!
                 * @brief Default destructor.
                 */
                eProsima_user_DllExport ~LowState_();

                /*!
                 * @brief Copy constructor.
                 * @param x Reference to the object booster_interface::msg::dds_::LowState_ that will be copied.
                 */
                eProsima_user_DllExport LowState_(
                        const LowState_& x);

                /*!
                 * @brief Move constructor.
                 * @param x Reference to the object booster_interface::msg::dds_::LowState_ that will be copied.
                 */
                eProsima_user_DllExport LowState_(
                        LowState_&& x) noexcept;

                /*!
                 * @brief Copy assignment.
                 * @param x Reference to the object booster_interface::msg::dds_::LowState_ that will be copied.
                 */
                eProsima_user_DllExport LowState_& operator =(
                        const LowState_& x);

                /*!
                 * @brief Move assignment.
                 * @param x Reference to the object booster_interface::msg::dds_::LowState_ that will be copied.
                 */
                eProsima_user_DllExport LowState_& operator =(
                        LowState_&& x) noexcept;

                /*!
                 * @brief Comparison operator.
                 * @param x booster_interface::msg::dds_::LowState_ object to compare.
                 */
                eProsima_user_DllExport bool operator ==(
                        const LowState_& x) const;

                /*!
                 * @brief Comparison operator.
                 * @param x booster_interface::msg::dds_::LowState_ object to compare.
                 */
                eProsima_user_DllExport bool operator !=(
                        const LowState_& x) const;

                /*!
                 * @brief This function copies the value in member imu_state
                 * @param _imu_state New value to be copied in member imu_state
                 */
                eProsima_user_DllExport void imu_state(
                        const booster_interface::msg::dds_::ImuState_& _imu_state);

                /*!
                 * @brief This function moves the value in member imu_state
                 * @param _imu_state New value to be moved in member imu_state
                 */
                eProsima_user_DllExport void imu_state(
                        booster_interface::msg::dds_::ImuState_&& _imu_state);

                /*!
                 * @brief This function returns a constant reference to member imu_state
                 * @return Constant reference to member imu_state
                 */
                eProsima_user_DllExport const booster_interface::msg::dds_::ImuState_& imu_state() const;

                /*!
                 * @brief This function returns a reference to member imu_state
                 * @return Reference to member imu_state
                 */
                eProsima_user_DllExport booster_interface::msg::dds_::ImuState_& imu_state();


                /*!
                 * @brief This function copies the value in member motor_state_parallel
                 * @param _motor_state_parallel New value to be copied in member motor_state_parallel
                 */
                eProsima_user_DllExport void motor_state_parallel(
                        const std::vector<booster_interface::msg::dds_::MotorState_>& _motor_state_parallel);

                /*!
                 * @brief This function moves the value in member motor_state_parallel
                 * @param _motor_state_parallel New value to be moved in member motor_state_parallel
                 */
                eProsima_user_DllExport void motor_state_parallel(
                        std::vector<booster_interface::msg::dds_::MotorState_>&& _motor_state_parallel);

                /*!
                 * @brief This function returns a constant reference to member motor_state_parallel
                 * @return Constant reference to member motor_state_parallel
                 */
                eProsima_user_DllExport const std::vector<booster_interface::msg::dds_::MotorState_>& motor_state_parallel() const;

                /*!
                 * @brief This function returns a reference to member motor_state_parallel
                 * @return Reference to member motor_state_parallel
                 */
                eProsima_user_DllExport std::vector<booster_interface::msg::dds_::MotorState_>& motor_state_parallel();


                /*!
                 * @brief This function copies the value in member motor_state_serial
                 * @param _motor_state_serial New value to be copied in member motor_state_serial
                 */
                eProsima_user_DllExport void motor_state_serial(
                        const std::vector<booster_interface::msg::dds_::MotorState_>& _motor_state_serial);

                /*!
                 * @brief This function moves the value in member motor_state_serial
                 * @param _motor_state_serial New value to be moved in member motor_state_serial
                 */
                eProsima_user_DllExport void motor_state_serial(
                        std::vector<booster_interface::msg::dds_::MotorState_>&& _motor_state_serial);

                /*!
                 * @brief This function returns a constant reference to member motor_state_serial
                 * @return Constant reference to member motor_state_serial
                 */
                eProsima_user_DllExport const std::vector<booster_interface::msg::dds_::MotorState_>& motor_state_serial() const;

                /*!
                 * @brief This function returns a reference to member motor_state_serial
                 * @return Reference to member motor_state_serial
                 */
                eProsima_user_DllExport std::vector<booster_interface::msg::dds_::MotorState_>& motor_state_serial();


                /*!
                * @brief This function returns the maximum serialized size of an object
                * depending on the buffer alignment.
                * @param current_alignment Buffer alignment.
                * @return Maximum serialized size.
                */
                eProsima_user_DllExport static size_t getMaxCdrSerializedSize(
                        size_t current_alignment = 0);

                /*!
                 * @brief This function returns the serialized size of a data depending on the buffer alignment.
                 * @param data Data which is calculated its serialized size.
                 * @param current_alignment Buffer alignment.
                 * @return Serialized size.
                 */
                eProsima_user_DllExport static size_t getCdrSerializedSize(
                        const booster_interface::msg::dds_::LowState_& data,
                        size_t current_alignment = 0);



                /*!
                 * @brief This function serializes an object using CDR serialization.
                 * @param cdr CDR serialization object.
                 */
                eProsima_user_DllExport void serialize(
                        eprosima::fastcdr::Cdr& cdr) const;

                /*!
                 * @brief This function deserializes an object using CDR serialization.
                 * @param cdr CDR serialization object.
                 */
                eProsima_user_DllExport void deserialize(
                        eprosima::fastcdr::Cdr& cdr);




                /*!
                * @brief This function tells you if the Key has been defined for this type
                */
                eProsima_user_DllExport static bool isKeyDefined();

                /*!
                * @brief This function serializes the key members of an object using CDR serialization.
                * @param cdr CDR serialization object.
                */
                eProsima_user_DllExport void serializeKey(
                        eprosima::fastcdr::Cdr& cdr) const;


            private:

                booster_interface::msg::dds_::ImuState_ m_imu_state;
                std::vector<booster_interface::msg::dds_::MotorState_> m_motor_state_parallel;
                std::vector<booster_interface::msg::dds_::MotorState_> m_motor_state_serial;

            };

        } // namespace dds_
    } // namespace msg
} // namespace booster_interface

#endif // _FAST_DDS_GENERATED_BOOSTER_INTERFACE_MSG_DDS__LOWSTATE_H_



