// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file MotorCmd.cpp
 * This source file contains the implementation of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "MotorCmd.h"

#include <fastcdr/Cdr.h>


#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

namespace helper { namespace internal {

enum class Size {
    UInt8,
    UInt16,
    UInt32,
    UInt64,
};

constexpr Size get_size(int s) {
    return (s <= 8 ) ? Size::UInt8:
           (s <= 16) ? Size::UInt16:
           (s <= 32) ? Size::UInt32: Size::UInt64;
}

template<Size s>
struct FindTypeH;

template<>
struct FindTypeH<Size::UInt8> {
    using type = std::uint8_t;
};

template<>
struct FindTypeH<Size::UInt16> {
    using type = std::uint16_t;
};

template<>
struct FindTypeH<Size::UInt32> {
    using type = std::uint32_t;
};

template<>
struct FindTypeH<Size::UInt64> {
    using type = std::uint64_t;
};
}

template<int S>
struct FindType {
    using type = typename internal::FindTypeH<internal::get_size(S)>::type;
};
}

#define booster_interface_msg_dds__MotorCmd__max_cdr_typesize 28ULL;


namespace booster_interface {

namespace msg {

namespace dds_ {



MotorCmd_::MotorCmd_()
{
    // octet m_mode
    m_mode = 0;
    // float m_q
    m_q = 0.0;
    // float m_dq
    m_dq = 0.0;
    // float m_tau
    m_tau = 0.0;
    // float m_kp
    m_kp = 0.0;
    // float m_kd
    m_kd = 0.0;
    // float m_weight
    m_weight = 0.0;

}

MotorCmd_::~MotorCmd_()
{
}

MotorCmd_::MotorCmd_(
        const MotorCmd_& x)
{
    m_mode = x.m_mode;


    m_q = x.m_q;


    m_dq = x.m_dq;


    m_tau = x.m_tau;


    m_kp = x.m_kp;


    m_kd = x.m_kd;


    m_weight = x.m_weight;

}

MotorCmd_::MotorCmd_(
        MotorCmd_&& x) noexcept
{
    m_mode = x.m_mode;


    m_q = x.m_q;


    m_dq = x.m_dq;


    m_tau = x.m_tau;


    m_kp = x.m_kp;


    m_kd = x.m_kd;


    m_weight = x.m_weight;

}

MotorCmd_& MotorCmd_::operator =(
        const MotorCmd_& x)
{
    m_mode = x.m_mode;


    m_q = x.m_q;


    m_dq = x.m_dq;


    m_tau = x.m_tau;


    m_kp = x.m_kp;


    m_kd = x.m_kd;


    m_weight = x.m_weight;

    return *this;
}

MotorCmd_& MotorCmd_::operator =(
        MotorCmd_&& x) noexcept
{
    m_mode = x.m_mode;


    m_q = x.m_q;


    m_dq = x.m_dq;


    m_tau = x.m_tau;


    m_kp = x.m_kp;


    m_kd = x.m_kd;


    m_weight = x.m_weight;

    return *this;
}

bool MotorCmd_::operator ==(
        const MotorCmd_& x) const
{
    return (m_mode == x.m_mode &&
           m_q == x.m_q &&
           m_dq == x.m_dq &&
           m_tau == x.m_tau &&
           m_kp == x.m_kp &&
           m_kd == x.m_kd &&
           m_weight == x.m_weight);
}

bool MotorCmd_::operator !=(
        const MotorCmd_& x) const
{
    return !(*this == x);
}

size_t MotorCmd_::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    static_cast<void>(current_alignment);
    return booster_interface_msg_dds__MotorCmd__max_cdr_typesize;
}

size_t MotorCmd_::getCdrSerializedSize(
        const MotorCmd_& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;

    current_alignment += 1 + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    return current_alignment - initial_alignment;
}


void MotorCmd_::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{
    scdr << m_mode;

    scdr << m_q;

    scdr << m_dq;

    scdr << m_tau;

    scdr << m_kp;

    scdr << m_kd;

    scdr << m_weight;

}

void MotorCmd_::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{
    dcdr >> m_mode;



    dcdr >> m_q;



    dcdr >> m_dq;



    dcdr >> m_tau;



    dcdr >> m_kp;



    dcdr >> m_kd;



    dcdr >> m_weight;


}


bool MotorCmd_::isKeyDefined()
{
    return false;
}

void MotorCmd_::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
}

/*!
 * @brief This function sets a value in member mode
 * @param _mode New value for member mode
 */
void MotorCmd_::mode(
        uint8_t _mode)
{
    m_mode = _mode;
}

/*!
 * @brief This function returns the value of member mode
 * @return Value of member mode
 */
uint8_t MotorCmd_::mode() const
{
    return m_mode;
}

/*!
 * @brief This function returns a reference to member mode
 * @return Reference to member mode
 */
uint8_t& MotorCmd_::mode()
{
    return m_mode;
}


/*!
 * @brief This function sets a value in member q
 * @param _q New value for member q
 */
void MotorCmd_::q(
        float _q)
{
    m_q = _q;
}

/*!
 * @brief This function returns the value of member q
 * @return Value of member q
 */
float MotorCmd_::q() const
{
    return m_q;
}

/*!
 * @brief This function returns a reference to member q
 * @return Reference to member q
 */
float& MotorCmd_::q()
{
    return m_q;
}


/*!
 * @brief This function sets a value in member dq
 * @param _dq New value for member dq
 */
void MotorCmd_::dq(
        float _dq)
{
    m_dq = _dq;
}

/*!
 * @brief This function returns the value of member dq
 * @return Value of member dq
 */
float MotorCmd_::dq() const
{
    return m_dq;
}

/*!
 * @brief This function returns a reference to member dq
 * @return Reference to member dq
 */
float& MotorCmd_::dq()
{
    return m_dq;
}


/*!
 * @brief This function sets a value in member tau
 * @param _tau New value for member tau
 */
void MotorCmd_::tau(
        float _tau)
{
    m_tau = _tau;
}

/*!
 * @brief This function returns the value of member tau
 * @return Value of member tau
 */
float MotorCmd_::tau() const
{
    return m_tau;
}

/*!
 * @brief This function returns a reference to member tau
 * @return Reference to member tau
 */
float& MotorCmd_::tau()
{
    return m_tau;
}


/*!
 * @brief This function sets a value in member kp
 * @param _kp New value for member kp
 */
void MotorCmd_::kp(
        float _kp)
{
    m_kp = _kp;
}

/*!
 * @brief This function returns the value of member kp
 * @return Value of member kp
 */
float MotorCmd_::kp() const
{
    return m_kp;
}

/*!
 * @brief This function returns a reference to member kp
 * @return Reference to member kp
 */
float& MotorCmd_::kp()
{
    return m_kp;
}


/*!
 * @brief This function sets a value in member kd
 * @param _kd New value for member kd
 */
void MotorCmd_::kd(
        float _kd)
{
    m_kd = _kd;
}

/*!
 * @brief This function returns the value of member kd
 * @return Value of member kd
 */
float MotorCmd_::kd() const
{
    return m_kd;
}

/*!
 * @brief This function returns a reference to member kd
 * @return Reference to member kd
 */
float& MotorCmd_::kd()
{
    return m_kd;
}


/*!
 * @brief This function sets a value in member weight
 * @param _weight New value for member weight
 */
void MotorCmd_::weight(
        float _weight)
{
    m_weight = _weight;
}

/*!
 * @brief This function returns the value of member weight
 * @return Value of member weight
 */
float MotorCmd_::weight() const
{
    return m_weight;
}

/*!
 * @brief This function returns a reference to member weight
 * @return Reference to member weight
 */
float& MotorCmd_::weight()
{
    return m_weight;
}





} // namespace dds_


} // namespace msg


} // namespace booster_interface

