// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file MotorState.cpp
 * This source file contains the implementation of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "MotorState.h"

#include <fastcdr/Cdr.h>


#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

namespace helper { namespace internal {

enum class Size {
    UInt8,
    UInt16,
    UInt32,
    UInt64,
};

constexpr Size get_size(int s) {
    return (s <= 8 ) ? Size::UInt8:
           (s <= 16) ? Size::UInt16:
           (s <= 32) ? Size::UInt32: Size::UInt64;
}

template<Size s>
struct FindTypeH;

template<>
struct FindTypeH<Size::UInt8> {
    using type = std::uint8_t;
};

template<>
struct FindTypeH<Size::UInt16> {
    using type = std::uint16_t;
};

template<>
struct FindTypeH<Size::UInt32> {
    using type = std::uint32_t;
};

template<>
struct FindTypeH<Size::UInt64> {
    using type = std::uint64_t;
};
}

template<int S>
struct FindType {
    using type = typename internal::FindTypeH<internal::get_size(S)>::type;
};
}

#define booster_interface_msg_dds__MotorState__max_cdr_typesize 36ULL;


namespace booster_interface {

namespace msg {

namespace dds_ {



MotorState_::MotorState_()
{
    // octet m_mode
    m_mode = 0;
    // float m_q
    m_q = 0.0;
    // float m_dq
    m_dq = 0.0;
    // float m_ddq
    m_ddq = 0.0;
    // float m_tau_est
    m_tau_est = 0.0;
    // octet m_temperature
    m_temperature = 0;
    // unsigned long m_lost
    m_lost = 0;
    // unsigned long m_reserve
    memset(&m_reserve, 0, ((2)) * 4);

}

MotorState_::~MotorState_()
{
}

MotorState_::MotorState_(
        const MotorState_& x)
{
    m_mode = x.m_mode;


    m_q = x.m_q;


    m_dq = x.m_dq;


    m_ddq = x.m_ddq;


    m_tau_est = x.m_tau_est;


    m_temperature = x.m_temperature;


    m_lost = x.m_lost;


    m_reserve = x.m_reserve;

}

MotorState_::MotorState_(
        MotorState_&& x) noexcept
{
    m_mode = x.m_mode;


    m_q = x.m_q;


    m_dq = x.m_dq;


    m_ddq = x.m_ddq;


    m_tau_est = x.m_tau_est;


    m_temperature = x.m_temperature;


    m_lost = x.m_lost;


    m_reserve = std::move(x.m_reserve);

}

MotorState_& MotorState_::operator =(
        const MotorState_& x)
{
    m_mode = x.m_mode;


    m_q = x.m_q;


    m_dq = x.m_dq;


    m_ddq = x.m_ddq;


    m_tau_est = x.m_tau_est;


    m_temperature = x.m_temperature;


    m_lost = x.m_lost;


    m_reserve = x.m_reserve;

    return *this;
}

MotorState_& MotorState_::operator =(
        MotorState_&& x) noexcept
{
    m_mode = x.m_mode;


    m_q = x.m_q;


    m_dq = x.m_dq;


    m_ddq = x.m_ddq;


    m_tau_est = x.m_tau_est;


    m_temperature = x.m_temperature;


    m_lost = x.m_lost;


    m_reserve = std::move(x.m_reserve);

    return *this;
}

bool MotorState_::operator ==(
        const MotorState_& x) const
{
    return (m_mode == x.m_mode &&
           m_q == x.m_q &&
           m_dq == x.m_dq &&
           m_ddq == x.m_ddq &&
           m_tau_est == x.m_tau_est &&
           m_temperature == x.m_temperature &&
           m_lost == x.m_lost &&
           m_reserve == x.m_reserve);
}

bool MotorState_::operator !=(
        const MotorState_& x) const
{
    return !(*this == x);
}

size_t MotorState_::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    static_cast<void>(current_alignment);
    return booster_interface_msg_dds__MotorState__max_cdr_typesize;
}

size_t MotorState_::getCdrSerializedSize(
        const MotorState_& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;

    current_alignment += 1 + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 1 + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += (((2)) * 4) + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);



    return current_alignment - initial_alignment;
}


void MotorState_::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{
    scdr << m_mode;

    scdr << m_q;

    scdr << m_dq;

    scdr << m_ddq;

    scdr << m_tau_est;

    scdr << m_temperature;

    scdr << m_lost;

    scdr << m_reserve;


}

void MotorState_::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{
    dcdr >> m_mode;



    dcdr >> m_q;



    dcdr >> m_dq;



    dcdr >> m_ddq;



    dcdr >> m_tau_est;



    dcdr >> m_temperature;



    dcdr >> m_lost;



    dcdr >> m_reserve;


}


bool MotorState_::isKeyDefined()
{
    return false;
}

void MotorState_::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
}

/*!
 * @brief This function sets a value in member mode
 * @param _mode New value for member mode
 */
void MotorState_::mode(
        uint8_t _mode)
{
    m_mode = _mode;
}

/*!
 * @brief This function returns the value of member mode
 * @return Value of member mode
 */
uint8_t MotorState_::mode() const
{
    return m_mode;
}

/*!
 * @brief This function returns a reference to member mode
 * @return Reference to member mode
 */
uint8_t& MotorState_::mode()
{
    return m_mode;
}


/*!
 * @brief This function sets a value in member q
 * @param _q New value for member q
 */
void MotorState_::q(
        float _q)
{
    m_q = _q;
}

/*!
 * @brief This function returns the value of member q
 * @return Value of member q
 */
float MotorState_::q() const
{
    return m_q;
}

/*!
 * @brief This function returns a reference to member q
 * @return Reference to member q
 */
float& MotorState_::q()
{
    return m_q;
}


/*!
 * @brief This function sets a value in member dq
 * @param _dq New value for member dq
 */
void MotorState_::dq(
        float _dq)
{
    m_dq = _dq;
}

/*!
 * @brief This function returns the value of member dq
 * @return Value of member dq
 */
float MotorState_::dq() const
{
    return m_dq;
}

/*!
 * @brief This function returns a reference to member dq
 * @return Reference to member dq
 */
float& MotorState_::dq()
{
    return m_dq;
}


/*!
 * @brief This function sets a value in member ddq
 * @param _ddq New value for member ddq
 */
void MotorState_::ddq(
        float _ddq)
{
    m_ddq = _ddq;
}

/*!
 * @brief This function returns the value of member ddq
 * @return Value of member ddq
 */
float MotorState_::ddq() const
{
    return m_ddq;
}

/*!
 * @brief This function returns a reference to member ddq
 * @return Reference to member ddq
 */
float& MotorState_::ddq()
{
    return m_ddq;
}


/*!
 * @brief This function sets a value in member tau_est
 * @param _tau_est New value for member tau_est
 */
void MotorState_::tau_est(
        float _tau_est)
{
    m_tau_est = _tau_est;
}

/*!
 * @brief This function returns the value of member tau_est
 * @return Value of member tau_est
 */
float MotorState_::tau_est() const
{
    return m_tau_est;
}

/*!
 * @brief This function returns a reference to member tau_est
 * @return Reference to member tau_est
 */
float& MotorState_::tau_est()
{
    return m_tau_est;
}


/*!
 * @brief This function sets a value in member temperature
 * @param _temperature New value for member temperature
 */
void MotorState_::temperature(
        uint8_t _temperature)
{
    m_temperature = _temperature;
}

/*!
 * @brief This function returns the value of member temperature
 * @return Value of member temperature
 */
uint8_t MotorState_::temperature() const
{
    return m_temperature;
}

/*!
 * @brief This function returns a reference to member temperature
 * @return Reference to member temperature
 */
uint8_t& MotorState_::temperature()
{
    return m_temperature;
}


/*!
 * @brief This function sets a value in member lost
 * @param _lost New value for member lost
 */
void MotorState_::lost(
        uint32_t _lost)
{
    m_lost = _lost;
}

/*!
 * @brief This function returns the value of member lost
 * @return Value of member lost
 */
uint32_t MotorState_::lost() const
{
    return m_lost;
}

/*!
 * @brief This function returns a reference to member lost
 * @return Reference to member lost
 */
uint32_t& MotorState_::lost()
{
    return m_lost;
}


/*!
 * @brief This function copies the value in member reserve
 * @param _reserve New value to be copied in member reserve
 */
void MotorState_::reserve(
        const std::array<uint32_t, 2>& _reserve)
{
    m_reserve = _reserve;
}

/*!
 * @brief This function moves the value in member reserve
 * @param _reserve New value to be moved in member reserve
 */
void MotorState_::reserve(
        std::array<uint32_t, 2>&& _reserve)
{
    m_reserve = std::move(_reserve);
}

/*!
 * @brief This function returns a constant reference to member reserve
 * @return Constant reference to member reserve
 */
const std::array<uint32_t, 2>& MotorState_::reserve() const
{
    return m_reserve;
}

/*!
 * @brief This function returns a reference to member reserve
 * @return Reference to member reserve
 */
std::array<uint32_t, 2>& MotorState_::reserve()
{
    return m_reserve;
}





} // namespace dds_


} // namespace msg


} // namespace booster_interface

