// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file MotorCmd.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef _FAST_DDS_GENERATED_BOOSTER_INTERFACE_MSG_DDS__MOTORCMD_H_
#define _FAST_DDS_GENERATED_BOOSTER_INTERFACE_MSG_DDS__MOTORCMD_H_


#include <fastrtps/utils/fixed_size_string.hpp>

#include <stdint.h>
#include <array>
#include <string>
#include <vector>
#include <map>
#include <bitset>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(MOTORCMD_SOURCE)
#define MOTORCMD_DllAPI __declspec( dllexport )
#else
#define MOTORCMD_DllAPI __declspec( dllimport )
#endif // MOTORCMD_SOURCE
#else
#define MOTORCMD_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define MOTORCMD_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
} // namespace fastcdr
} // namespace eprosima



namespace booster_interface {
    namespace msg {
        namespace dds_ {


            /*!
             * @brief This class represents the structure MotorCmd_ defined by the user in the IDL file.
             * @ingroup MotorCmd
             */
            class MotorCmd_
            {
            public:

                /*!
                 * @brief Default constructor.
                 */
                eProsima_user_DllExport MotorCmd_();

                /*!
                 * @brief Default destructor.
                 */
                eProsima_user_DllExport ~MotorCmd_();

                /*!
                 * @brief Copy constructor.
                 * @param x Reference to the object booster_interface::msg::dds_::MotorCmd_ that will be copied.
                 */
                eProsima_user_DllExport MotorCmd_(
                        const MotorCmd_& x);

                /*!
                 * @brief Move constructor.
                 * @param x Reference to the object booster_interface::msg::dds_::MotorCmd_ that will be copied.
                 */
                eProsima_user_DllExport MotorCmd_(
                        MotorCmd_&& x) noexcept;

                /*!
                 * @brief Copy assignment.
                 * @param x Reference to the object booster_interface::msg::dds_::MotorCmd_ that will be copied.
                 */
                eProsima_user_DllExport MotorCmd_& operator =(
                        const MotorCmd_& x);

                /*!
                 * @brief Move assignment.
                 * @param x Reference to the object booster_interface::msg::dds_::MotorCmd_ that will be copied.
                 */
                eProsima_user_DllExport MotorCmd_& operator =(
                        MotorCmd_&& x) noexcept;

                /*!
                 * @brief Comparison operator.
                 * @param x booster_interface::msg::dds_::MotorCmd_ object to compare.
                 */
                eProsima_user_DllExport bool operator ==(
                        const MotorCmd_& x) const;

                /*!
                 * @brief Comparison operator.
                 * @param x booster_interface::msg::dds_::MotorCmd_ object to compare.
                 */
                eProsima_user_DllExport bool operator !=(
                        const MotorCmd_& x) const;

                /*!
                 * @brief This function sets a value in member mode
                 * @param _mode New value for member mode
                 */
                eProsima_user_DllExport void mode(
                        uint8_t _mode);

                /*!
                 * @brief This function returns the value of member mode
                 * @return Value of member mode
                 */
                eProsima_user_DllExport uint8_t mode() const;

                /*!
                 * @brief This function returns a reference to member mode
                 * @return Reference to member mode
                 */
                eProsima_user_DllExport uint8_t& mode();


                /*!
                 * @brief This function sets a value in member q
                 * @param _q New value for member q
                 */
                eProsima_user_DllExport void q(
                        float _q);

                /*!
                 * @brief This function returns the value of member q
                 * @return Value of member q
                 */
                eProsima_user_DllExport float q() const;

                /*!
                 * @brief This function returns a reference to member q
                 * @return Reference to member q
                 */
                eProsima_user_DllExport float& q();


                /*!
                 * @brief This function sets a value in member dq
                 * @param _dq New value for member dq
                 */
                eProsima_user_DllExport void dq(
                        float _dq);

                /*!
                 * @brief This function returns the value of member dq
                 * @return Value of member dq
                 */
                eProsima_user_DllExport float dq() const;

                /*!
                 * @brief This function returns a reference to member dq
                 * @return Reference to member dq
                 */
                eProsima_user_DllExport float& dq();


                /*!
                 * @brief This function sets a value in member tau
                 * @param _tau New value for member tau
                 */
                eProsima_user_DllExport void tau(
                        float _tau);

                /*!
                 * @brief This function returns the value of member tau
                 * @return Value of member tau
                 */
                eProsima_user_DllExport float tau() const;

                /*!
                 * @brief This function returns a reference to member tau
                 * @return Reference to member tau
                 */
                eProsima_user_DllExport float& tau();


                /*!
                 * @brief This function sets a value in member kp
                 * @param _kp New value for member kp
                 */
                eProsima_user_DllExport void kp(
                        float _kp);

                /*!
                 * @brief This function returns the value of member kp
                 * @return Value of member kp
                 */
                eProsima_user_DllExport float kp() const;

                /*!
                 * @brief This function returns a reference to member kp
                 * @return Reference to member kp
                 */
                eProsima_user_DllExport float& kp();


                /*!
                 * @brief This function sets a value in member kd
                 * @param _kd New value for member kd
                 */
                eProsima_user_DllExport void kd(
                        float _kd);

                /*!
                 * @brief This function returns the value of member kd
                 * @return Value of member kd
                 */
                eProsima_user_DllExport float kd() const;

                /*!
                 * @brief This function returns a reference to member kd
                 * @return Reference to member kd
                 */
                eProsima_user_DllExport float& kd();


                /*!
                 * @brief This function sets a value in member weight
                 * @param _weight New value for member weight
                 */
                eProsima_user_DllExport void weight(
                        float _weight);

                /*!
                 * @brief This function returns the value of member weight
                 * @return Value of member weight
                 */
                eProsima_user_DllExport float weight() const;

                /*!
                 * @brief This function returns a reference to member weight
                 * @return Reference to member weight
                 */
                eProsima_user_DllExport float& weight();


                /*!
                * @brief This function returns the maximum serialized size of an object
                * depending on the buffer alignment.
                * @param current_alignment Buffer alignment.
                * @return Maximum serialized size.
                */
                eProsima_user_DllExport static size_t getMaxCdrSerializedSize(
                        size_t current_alignment = 0);

                /*!
                 * @brief This function returns the serialized size of a data depending on the buffer alignment.
                 * @param data Data which is calculated its serialized size.
                 * @param current_alignment Buffer alignment.
                 * @return Serialized size.
                 */
                eProsima_user_DllExport static size_t getCdrSerializedSize(
                        const booster_interface::msg::dds_::MotorCmd_& data,
                        size_t current_alignment = 0);



                /*!
                 * @brief This function serializes an object using CDR serialization.
                 * @param cdr CDR serialization object.
                 */
                eProsima_user_DllExport void serialize(
                        eprosima::fastcdr::Cdr& cdr) const;

                /*!
                 * @brief This function deserializes an object using CDR serialization.
                 * @param cdr CDR serialization object.
                 */
                eProsima_user_DllExport void deserialize(
                        eprosima::fastcdr::Cdr& cdr);




                /*!
                * @brief This function tells you if the Key has been defined for this type
                */
                eProsima_user_DllExport static bool isKeyDefined();

                /*!
                * @brief This function serializes the key members of an object using CDR serialization.
                * @param cdr CDR serialization object.
                */
                eProsima_user_DllExport void serializeKey(
                        eprosima::fastcdr::Cdr& cdr) const;


            private:

                uint8_t m_mode;
                float m_q;
                float m_dq;
                float m_tau;
                float m_kp;
                float m_kd;
                float m_weight;

            };

        } // namespace dds_
    } // namespace msg
} // namespace booster_interface

#endif // _FAST_DDS_GENERATED_BOOSTER_INTERFACE_MSG_DDS__MOTORCMD_H_



