// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file MotorState.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef _FAST_DDS_GENERATED_BOOSTER_INTERFACE_MSG_DDS__MOTORSTATE_H_
#define _FAST_DDS_GENERATED_BOOSTER_INTERFACE_MSG_DDS__MOTORSTATE_H_


#include <fastrtps/utils/fixed_size_string.hpp>

#include <stdint.h>
#include <array>
#include <string>
#include <vector>
#include <map>
#include <bitset>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(MOTORSTATE_SOURCE)
#define MOTORSTATE_DllAPI __declspec( dllexport )
#else
#define MOTORSTATE_DllAPI __declspec( dllimport )
#endif // MOTORSTATE_SOURCE
#else
#define MOTORSTATE_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define MOTORSTATE_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
} // namespace fastcdr
} // namespace eprosima



namespace booster_interface {
    namespace msg {
        namespace dds_ {


            /*!
             * @brief This class represents the structure MotorState_ defined by the user in the IDL file.
             * @ingroup MotorState
             */
            class MotorState_
            {
            public:

                /*!
                 * @brief Default constructor.
                 */
                eProsima_user_DllExport MotorState_();

                /*!
                 * @brief Default destructor.
                 */
                eProsima_user_DllExport ~MotorState_();

                /*!
                 * @brief Copy constructor.
                 * @param x Reference to the object booster_interface::msg::dds_::MotorState_ that will be copied.
                 */
                eProsima_user_DllExport MotorState_(
                        const MotorState_& x);

                /*!
                 * @brief Move constructor.
                 * @param x Reference to the object booster_interface::msg::dds_::MotorState_ that will be copied.
                 */
                eProsima_user_DllExport MotorState_(
                        MotorState_&& x) noexcept;

                /*!
                 * @brief Copy assignment.
                 * @param x Reference to the object booster_interface::msg::dds_::MotorState_ that will be copied.
                 */
                eProsima_user_DllExport MotorState_& operator =(
                        const MotorState_& x);

                /*!
                 * @brief Move assignment.
                 * @param x Reference to the object booster_interface::msg::dds_::MotorState_ that will be copied.
                 */
                eProsima_user_DllExport MotorState_& operator =(
                        MotorState_&& x) noexcept;

                /*!
                 * @brief Comparison operator.
                 * @param x booster_interface::msg::dds_::MotorState_ object to compare.
                 */
                eProsima_user_DllExport bool operator ==(
                        const MotorState_& x) const;

                /*!
                 * @brief Comparison operator.
                 * @param x booster_interface::msg::dds_::MotorState_ object to compare.
                 */
                eProsima_user_DllExport bool operator !=(
                        const MotorState_& x) const;

                /*!
                 * @brief This function sets a value in member mode
                 * @param _mode New value for member mode
                 */
                eProsima_user_DllExport void mode(
                        uint8_t _mode);

                /*!
                 * @brief This function returns the value of member mode
                 * @return Value of member mode
                 */
                eProsima_user_DllExport uint8_t mode() const;

                /*!
                 * @brief This function returns a reference to member mode
                 * @return Reference to member mode
                 */
                eProsima_user_DllExport uint8_t& mode();


                /*!
                 * @brief This function sets a value in member q
                 * @param _q New value for member q
                 */
                eProsima_user_DllExport void q(
                        float _q);

                /*!
                 * @brief This function returns the value of member q
                 * @return Value of member q
                 */
                eProsima_user_DllExport float q() const;

                /*!
                 * @brief This function returns a reference to member q
                 * @return Reference to member q
                 */
                eProsima_user_DllExport float& q();


                /*!
                 * @brief This function sets a value in member dq
                 * @param _dq New value for member dq
                 */
                eProsima_user_DllExport void dq(
                        float _dq);

                /*!
                 * @brief This function returns the value of member dq
                 * @return Value of member dq
                 */
                eProsima_user_DllExport float dq() const;

                /*!
                 * @brief This function returns a reference to member dq
                 * @return Reference to member dq
                 */
                eProsima_user_DllExport float& dq();


                /*!
                 * @brief This function sets a value in member ddq
                 * @param _ddq New value for member ddq
                 */
                eProsima_user_DllExport void ddq(
                        float _ddq);

                /*!
                 * @brief This function returns the value of member ddq
                 * @return Value of member ddq
                 */
                eProsima_user_DllExport float ddq() const;

                /*!
                 * @brief This function returns a reference to member ddq
                 * @return Reference to member ddq
                 */
                eProsima_user_DllExport float& ddq();


                /*!
                 * @brief This function sets a value in member tau_est
                 * @param _tau_est New value for member tau_est
                 */
                eProsima_user_DllExport void tau_est(
                        float _tau_est);

                /*!
                 * @brief This function returns the value of member tau_est
                 * @return Value of member tau_est
                 */
                eProsima_user_DllExport float tau_est() const;

                /*!
                 * @brief This function returns a reference to member tau_est
                 * @return Reference to member tau_est
                 */
                eProsima_user_DllExport float& tau_est();


                /*!
                 * @brief This function sets a value in member temperature
                 * @param _temperature New value for member temperature
                 */
                eProsima_user_DllExport void temperature(
                        uint8_t _temperature);

                /*!
                 * @brief This function returns the value of member temperature
                 * @return Value of member temperature
                 */
                eProsima_user_DllExport uint8_t temperature() const;

                /*!
                 * @brief This function returns a reference to member temperature
                 * @return Reference to member temperature
                 */
                eProsima_user_DllExport uint8_t& temperature();


                /*!
                 * @brief This function sets a value in member lost
                 * @param _lost New value for member lost
                 */
                eProsima_user_DllExport void lost(
                        uint32_t _lost);

                /*!
                 * @brief This function returns the value of member lost
                 * @return Value of member lost
                 */
                eProsima_user_DllExport uint32_t lost() const;

                /*!
                 * @brief This function returns a reference to member lost
                 * @return Reference to member lost
                 */
                eProsima_user_DllExport uint32_t& lost();


                /*!
                 * @brief This function copies the value in member reserve
                 * @param _reserve New value to be copied in member reserve
                 */
                eProsima_user_DllExport void reserve(
                        const std::array<uint32_t, 2>& _reserve);

                /*!
                 * @brief This function moves the value in member reserve
                 * @param _reserve New value to be moved in member reserve
                 */
                eProsima_user_DllExport void reserve(
                        std::array<uint32_t, 2>&& _reserve);

                /*!
                 * @brief This function returns a constant reference to member reserve
                 * @return Constant reference to member reserve
                 */
                eProsima_user_DllExport const std::array<uint32_t, 2>& reserve() const;

                /*!
                 * @brief This function returns a reference to member reserve
                 * @return Reference to member reserve
                 */
                eProsima_user_DllExport std::array<uint32_t, 2>& reserve();


                /*!
                * @brief This function returns the maximum serialized size of an object
                * depending on the buffer alignment.
                * @param current_alignment Buffer alignment.
                * @return Maximum serialized size.
                */
                eProsima_user_DllExport static size_t getMaxCdrSerializedSize(
                        size_t current_alignment = 0);

                /*!
                 * @brief This function returns the serialized size of a data depending on the buffer alignment.
                 * @param data Data which is calculated its serialized size.
                 * @param current_alignment Buffer alignment.
                 * @return Serialized size.
                 */
                eProsima_user_DllExport static size_t getCdrSerializedSize(
                        const booster_interface::msg::dds_::MotorState_& data,
                        size_t current_alignment = 0);



                /*!
                 * @brief This function serializes an object using CDR serialization.
                 * @param cdr CDR serialization object.
                 */
                eProsima_user_DllExport void serialize(
                        eprosima::fastcdr::Cdr& cdr) const;

                /*!
                 * @brief This function deserializes an object using CDR serialization.
                 * @param cdr CDR serialization object.
                 */
                eProsima_user_DllExport void deserialize(
                        eprosima::fastcdr::Cdr& cdr);




                /*!
                * @brief This function tells you if the Key has been defined for this type
                */
                eProsima_user_DllExport static bool isKeyDefined();

                /*!
                * @brief This function serializes the key members of an object using CDR serialization.
                * @param cdr CDR serialization object.
                */
                eProsima_user_DllExport void serializeKey(
                        eprosima::fastcdr::Cdr& cdr) const;


            private:

                uint8_t m_mode;
                float m_q;
                float m_dq;
                float m_ddq;
                float m_tau_est;
                uint8_t m_temperature;
                uint32_t m_lost;
                std::array<uint32_t, 2> m_reserve;

            };

        } // namespace dds_
    } // namespace msg
} // namespace booster_interface

#endif // _FAST_DDS_GENERATED_BOOSTER_INTERFACE_MSG_DDS__MOTORSTATE_H_



