// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file Odometer.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef _FAST_DDS_GENERATED_BOOSTER_INTERFACE_MSG_DDS__ODOMETER_H_
#define _FAST_DDS_GENERATED_BOOSTER_INTERFACE_MSG_DDS__ODOMETER_H_


#include <fastrtps/utils/fixed_size_string.hpp>

#include <stdint.h>
#include <array>
#include <string>
#include <vector>
#include <map>
#include <bitset>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(ODOMETER_SOURCE)
#define ODOMETER_DllAPI __declspec( dllexport )
#else
#define ODOMETER_DllAPI __declspec( dllimport )
#endif // ODOMETER_SOURCE
#else
#define ODOMETER_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define ODOMETER_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
} // namespace fastcdr
} // namespace eprosima



namespace booster_interface {
    namespace msg {
        namespace dds_ {


            /*!
             * @brief This class represents the structure Odometer_ defined by the user in the IDL file.
             * @ingroup Odometer
             */
            class Odometer_
            {
            public:

                /*!
                 * @brief Default constructor.
                 */
                eProsima_user_DllExport Odometer_();

                /*!
                 * @brief Default destructor.
                 */
                eProsima_user_DllExport ~Odometer_();

                /*!
                 * @brief Copy constructor.
                 * @param x Reference to the object booster_interface::msg::dds_::Odometer_ that will be copied.
                 */
                eProsima_user_DllExport Odometer_(
                        const Odometer_& x);

                /*!
                 * @brief Move constructor.
                 * @param x Reference to the object booster_interface::msg::dds_::Odometer_ that will be copied.
                 */
                eProsima_user_DllExport Odometer_(
                        Odometer_&& x) noexcept;

                /*!
                 * @brief Copy assignment.
                 * @param x Reference to the object booster_interface::msg::dds_::Odometer_ that will be copied.
                 */
                eProsima_user_DllExport Odometer_& operator =(
                        const Odometer_& x);

                /*!
                 * @brief Move assignment.
                 * @param x Reference to the object booster_interface::msg::dds_::Odometer_ that will be copied.
                 */
                eProsima_user_DllExport Odometer_& operator =(
                        Odometer_&& x) noexcept;

                /*!
                 * @brief Comparison operator.
                 * @param x booster_interface::msg::dds_::Odometer_ object to compare.
                 */
                eProsima_user_DllExport bool operator ==(
                        const Odometer_& x) const;

                /*!
                 * @brief Comparison operator.
                 * @param x booster_interface::msg::dds_::Odometer_ object to compare.
                 */
                eProsima_user_DllExport bool operator !=(
                        const Odometer_& x) const;

                /*!
                 * @brief This function sets a value in member x
                 * @param _x New value for member x
                 */
                eProsima_user_DllExport void x(
                        float _x);

                /*!
                 * @brief This function returns the value of member x
                 * @return Value of member x
                 */
                eProsima_user_DllExport float x() const;

                /*!
                 * @brief This function returns a reference to member x
                 * @return Reference to member x
                 */
                eProsima_user_DllExport float& x();


                /*!
                 * @brief This function sets a value in member y
                 * @param _y New value for member y
                 */
                eProsima_user_DllExport void y(
                        float _y);

                /*!
                 * @brief This function returns the value of member y
                 * @return Value of member y
                 */
                eProsima_user_DllExport float y() const;

                /*!
                 * @brief This function returns a reference to member y
                 * @return Reference to member y
                 */
                eProsima_user_DllExport float& y();


                /*!
                 * @brief This function sets a value in member theta
                 * @param _theta New value for member theta
                 */
                eProsima_user_DllExport void theta(
                        float _theta);

                /*!
                 * @brief This function returns the value of member theta
                 * @return Value of member theta
                 */
                eProsima_user_DllExport float theta() const;

                /*!
                 * @brief This function returns a reference to member theta
                 * @return Reference to member theta
                 */
                eProsima_user_DllExport float& theta();


                /*!
                * @brief This function returns the maximum serialized size of an object
                * depending on the buffer alignment.
                * @param current_alignment Buffer alignment.
                * @return Maximum serialized size.
                */
                eProsima_user_DllExport static size_t getMaxCdrSerializedSize(
                        size_t current_alignment = 0);

                /*!
                 * @brief This function returns the serialized size of a data depending on the buffer alignment.
                 * @param data Data which is calculated its serialized size.
                 * @param current_alignment Buffer alignment.
                 * @return Serialized size.
                 */
                eProsima_user_DllExport static size_t getCdrSerializedSize(
                        const booster_interface::msg::dds_::Odometer_& data,
                        size_t current_alignment = 0);



                /*!
                 * @brief This function serializes an object using CDR serialization.
                 * @param cdr CDR serialization object.
                 */
                eProsima_user_DllExport void serialize(
                        eprosima::fastcdr::Cdr& cdr) const;

                /*!
                 * @brief This function deserializes an object using CDR serialization.
                 * @param cdr CDR serialization object.
                 */
                eProsima_user_DllExport void deserialize(
                        eprosima::fastcdr::Cdr& cdr);




                /*!
                * @brief This function tells you if the Key has been defined for this type
                */
                eProsima_user_DllExport static bool isKeyDefined();

                /*!
                * @brief This function serializes the key members of an object using CDR serialization.
                * @param cdr CDR serialization object.
                */
                eProsima_user_DllExport void serializeKey(
                        eprosima::fastcdr::Cdr& cdr) const;


            private:

                float m_x;
                float m_y;
                float m_theta;

            };

        } // namespace dds_
    } // namespace msg
} // namespace booster_interface

#endif // _FAST_DDS_GENERATED_BOOSTER_INTERFACE_MSG_DDS__ODOMETER_H_



