// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file Odometer.cpp
 * This source file contains the implementation of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "Odometer.h"

#include <fastcdr/Cdr.h>


#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

namespace helper { namespace internal {

enum class Size {
    UInt8,
    UInt16,
    UInt32,
    UInt64,
};

constexpr Size get_size(int s) {
    return (s <= 8 ) ? Size::UInt8:
           (s <= 16) ? Size::UInt16:
           (s <= 32) ? Size::UInt32: Size::UInt64;
}

template<Size s>
struct FindTypeH;

template<>
struct FindTypeH<Size::UInt8> {
    using type = std::uint8_t;
};

template<>
struct FindTypeH<Size::UInt16> {
    using type = std::uint16_t;
};

template<>
struct FindTypeH<Size::UInt32> {
    using type = std::uint32_t;
};

template<>
struct FindTypeH<Size::UInt64> {
    using type = std::uint64_t;
};
}

template<int S>
struct FindType {
    using type = typename internal::FindTypeH<internal::get_size(S)>::type;
};
}

#define booster_interface_msg_dds__Odometer__max_cdr_typesize 12ULL;


namespace booster_interface {

namespace msg {

namespace dds_ {



Odometer_::Odometer_()
{
    // float m_x
    m_x = 0.0;
    // float m_y
    m_y = 0.0;
    // float m_theta
    m_theta = 0.0;

}

Odometer_::~Odometer_()
{
}

Odometer_::Odometer_(
        const Odometer_& x)
{
    m_x = x.m_x;


    m_y = x.m_y;


    m_theta = x.m_theta;

}

Odometer_::Odometer_(
        Odometer_&& x) noexcept
{
    m_x = x.m_x;


    m_y = x.m_y;


    m_theta = x.m_theta;

}

Odometer_& Odometer_::operator =(
        const Odometer_& x)
{
    m_x = x.m_x;


    m_y = x.m_y;


    m_theta = x.m_theta;

    return *this;
}

Odometer_& Odometer_::operator =(
        Odometer_&& x) noexcept
{
    m_x = x.m_x;


    m_y = x.m_y;


    m_theta = x.m_theta;

    return *this;
}

bool Odometer_::operator ==(
        const Odometer_& x) const
{
    return (m_x == x.m_x &&
           m_y == x.m_y &&
           m_theta == x.m_theta);
}

bool Odometer_::operator !=(
        const Odometer_& x) const
{
    return !(*this == x);
}

size_t Odometer_::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    static_cast<void>(current_alignment);
    return booster_interface_msg_dds__Odometer__max_cdr_typesize;
}

size_t Odometer_::getCdrSerializedSize(
        const Odometer_& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;

    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    return current_alignment - initial_alignment;
}


void Odometer_::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{
    scdr << m_x;

    scdr << m_y;

    scdr << m_theta;

}

void Odometer_::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{
    dcdr >> m_x;



    dcdr >> m_y;



    dcdr >> m_theta;


}


bool Odometer_::isKeyDefined()
{
    return false;
}

void Odometer_::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
}

/*!
 * @brief This function sets a value in member x
 * @param _x New value for member x
 */
void Odometer_::x(
        float _x)
{
    m_x = _x;
}

/*!
 * @brief This function returns the value of member x
 * @return Value of member x
 */
float Odometer_::x() const
{
    return m_x;
}

/*!
 * @brief This function returns a reference to member x
 * @return Reference to member x
 */
float& Odometer_::x()
{
    return m_x;
}


/*!
 * @brief This function sets a value in member y
 * @param _y New value for member y
 */
void Odometer_::y(
        float _y)
{
    m_y = _y;
}

/*!
 * @brief This function returns the value of member y
 * @return Value of member y
 */
float Odometer_::y() const
{
    return m_y;
}

/*!
 * @brief This function returns a reference to member y
 * @return Reference to member y
 */
float& Odometer_::y()
{
    return m_y;
}


/*!
 * @brief This function sets a value in member theta
 * @param _theta New value for member theta
 */
void Odometer_::theta(
        float _theta)
{
    m_theta = _theta;
}

/*!
 * @brief This function returns the value of member theta
 * @return Value of member theta
 */
float Odometer_::theta() const
{
    return m_theta;
}

/*!
 * @brief This function returns a reference to member theta
 * @return Reference to member theta
 */
float& Odometer_::theta()
{
    return m_theta;
}





} // namespace dds_


} // namespace msg


} // namespace booster_interface

